//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}cashier"/>
 *         &lt;element ref="{}posNum"/>
 *         &lt;element ref="{}cOpenTime"/>
 *         &lt;element ref="{}cCloseTime"/>
 *         &lt;element ref="{}beginTicket"/>
 *         &lt;element ref="{}endTicket"/>
 *         &lt;element ref="{}cashierPeriod"/>
 *         &lt;element ref="{}ticketCount"/>
 *         &lt;element ref="{}beginCash"/>
 *         &lt;element ref="{}beginFoodStmp"/>
 *         &lt;element ref="{}mwsEnabled" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cashier",
    "posNum",
    "cOpenTime",
    "cCloseTime",
    "beginTicket",
    "endTicket",
    "cashierPeriod",
    "ticketCount",
    "beginCash",
    "beginFoodStmp",
    "mwsEnabled"
})
@XmlRootElement(name = "closeCashier")
public class CloseCashier {

    @XmlElement(required = true)
    protected BaseCashierType cashier;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger posNum;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cOpenTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cCloseTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger beginTicket;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger endTicket;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger cashierPeriod;
    @XmlElement(required = true)
    protected Object ticketCount;
    @XmlElement(required = true)
    protected BeginCash beginCash;
    @XmlElement(required = true)
    protected BeginFoodStmp beginFoodStmp;
    protected BigInteger mwsEnabled;

    /**
     * Gets the value of the cashier property.
     * 
     * @return
     *     possible object is
     *     {@link BaseCashierType }
     *     
     */
    public BaseCashierType getCashier() {
        return cashier;
    }

    /**
     * Sets the value of the cashier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseCashierType }
     *     
     */
    public void setCashier(BaseCashierType value) {
        this.cashier = value;
    }

    /**
     * Gets the value of the posNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPosNum() {
        return posNum;
    }

    /**
     * Sets the value of the posNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPosNum(BigInteger value) {
        this.posNum = value;
    }

    /**
     * Gets the value of the cOpenTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCOpenTime() {
        return cOpenTime;
    }

    /**
     * Sets the value of the cOpenTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCOpenTime(XMLGregorianCalendar value) {
        this.cOpenTime = value;
    }

    /**
     * Gets the value of the cCloseTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCCloseTime() {
        return cCloseTime;
    }

    /**
     * Sets the value of the cCloseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCCloseTime(XMLGregorianCalendar value) {
        this.cCloseTime = value;
    }

    /**
     * Gets the value of the beginTicket property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBeginTicket() {
        return beginTicket;
    }

    /**
     * Sets the value of the beginTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBeginTicket(BigInteger value) {
        this.beginTicket = value;
    }

    /**
     * Gets the value of the endTicket property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEndTicket() {
        return endTicket;
    }

    /**
     * Sets the value of the endTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEndTicket(BigInteger value) {
        this.endTicket = value;
    }

    /**
     * Gets the value of the cashierPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCashierPeriod() {
        return cashierPeriod;
    }

    /**
     * Sets the value of the cashierPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCashierPeriod(BigInteger value) {
        this.cashierPeriod = value;
    }

    /**
     * Gets the value of the ticketCount property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTicketCount() {
        return ticketCount;
    }

    /**
     * Sets the value of the ticketCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTicketCount(Object value) {
        this.ticketCount = value;
    }

    /**
     * Gets the value of the beginCash property.
     * 
     * @return
     *     possible object is
     *     {@link BeginCash }
     *     
     */
    public BeginCash getBeginCash() {
        return beginCash;
    }

    /**
     * Sets the value of the beginCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeginCash }
     *     
     */
    public void setBeginCash(BeginCash value) {
        this.beginCash = value;
    }

    /**
     * Gets the value of the beginFoodStmp property.
     * 
     * @return
     *     possible object is
     *     {@link BeginFoodStmp }
     *     
     */
    public BeginFoodStmp getBeginFoodStmp() {
        return beginFoodStmp;
    }

    /**
     * Sets the value of the beginFoodStmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeginFoodStmp }
     *     
     */
    public void setBeginFoodStmp(BeginFoodStmp value) {
        this.beginFoodStmp = value;
    }

    /**
     * Gets the value of the mwsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMwsEnabled() {
        return mwsEnabled;
    }

    /**
     * Sets the value of the mwsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMwsEnabled(BigInteger value) {
        this.mwsEnabled = value;
    }

}
