//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.transset package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OriginalCashier_QNAME = new QName("", "originalCashier");
    private final static QName _TrlcblCwCd_QNAME = new QName("", "trlcblCwCd");
    private final static QName _TrlVoidLineIx_QNAME = new QName("", "trlVoidLineIx");
    private final static QName _StoreNumber_QNAME = new QName("", "storeNumber");
    private final static QName _TrTotNoTax_QNAME = new QName("", "trTotNoTax");
    private final static QName _TrPrePayComp_QNAME = new QName("", "trPrePayComp");
    private final static QName _TrlInvItemId_QNAME = new QName("", "trlInvItemId");
    private final static QName _InsideSales_QNAME = new QName("", "insideSales");
    private final static QName _ClosedTime_QNAME = new QName("", "closedTime");
    private final static QName _TrlcbBTime_QNAME = new QName("", "trlcbBTime");
    private final static QName _TrlNetwCode_QNAME = new QName("", "trlNetwCode");
    private final static QName _TrlXQty_QNAME = new QName("", "trlXQty");
    private final static QName _TrlFeeIdentifier_QNAME = new QName("", "trlFeeIdentifier");
    private final static QName _TrlcbPrice_QNAME = new QName("", "trlcbPrice");
    private final static QName _TrlcbNumber_QNAME = new QName("", "trlcbNumber");
    private final static QName _CashierPeriod_QNAME = new QName("", "cashierPeriod");
    private final static QName _TrClockOut_QNAME = new QName("", "trClockOut");
    private final static QName _TrlFuelSeq_QNAME = new QName("", "trlFuelSeq");
    private final static QName _TrlcblModfr_QNAME = new QName("", "trlcblModfr");
    private final static QName _OutsideGrand_QNAME = new QName("", "outsideGrand");
    private final static QName _TrlcblAmt_QNAME = new QName("", "trlcblAmt");
    private final static QName _EndTicket_QNAME = new QName("", "endTicket");
    private final static QName _TrlMOPayee_QNAME = new QName("", "trlMOPayee");
    private final static QName _PopDiscTran_QNAME = new QName("", "popDiscTran");
    private final static QName _TrlQty_QNAME = new QName("", "trlQty");
    private final static QName _TrMiscRefNum_QNAME = new QName("", "trMiscRefNum");
    private final static QName _TrlcblQty_QNAME = new QName("", "trlcblQty");
    private final static QName _TrlcbPcode_QNAME = new QName("", "trlcbPcode");
    private final static QName _PopCodeUsed_QNAME = new QName("", "popCodeUsed");
    private final static QName _TrlcblPrice_QNAME = new QName("", "trlcblPrice");
    private final static QName _OpenedTime_QNAME = new QName("", "openedTime");
    private final static QName _TrlpdDescrip_QNAME = new QName("", "trlpdDescrip");
    private final static QName _TrlpdGradeName_QNAME = new QName("", "trlpdGradeName");
    private final static QName _TrlcbDesc_QNAME = new QName("", "trlcbDesc");
    private final static QName _TrlFeeName_QNAME = new QName("", "trlFeeName");
    private final static QName _TicketCount_QNAME = new QName("", "ticketCount");
    private final static QName _TaxAmts_QNAME = new QName("", "taxAmts");
    private final static QName _ReconciledByID_QNAME = new QName("", "reconciledByID");
    private final static QName _TrClockIn_QNAME = new QName("", "trClockIn");
    private final static QName _FuelPosition_QNAME = new QName("", "fuelPosition");
    private final static QName _CustName_QNAME = new QName("", "custName");
    private final static QName _TrlSerialNum_QNAME = new QName("", "trlSerialNum");
    private final static QName _TrlpdFuelDef_QNAME = new QName("", "trlpdFuelDef");
    private final static QName _MwsEnabled_QNAME = new QName("", "mwsEnabled");
    private final static QName _TrlpdCodeUsed_QNAME = new QName("", "trlpdCodeUsed");
    private final static QName _TrOriginalTickNum_QNAME = new QName("", "trOriginalTickNum");
    private final static QName _TrlSign_QNAME = new QName("", "trlSign");
    private final static QName _OverallGrand_QNAME = new QName("", "overallGrand");
    private final static QName _TrlpdMemberID_QNAME = new QName("", "trlpdMemberID");
    private final static QName _Date_QNAME = new QName("", "date");
    private final static QName _TrHeader_QNAME = new QName("", "trHeader");
    private final static QName _Till_QNAME = new QName("", "till");
    private final static QName _TrlpdPGUnit_QNAME = new QName("", "trlpdPGUnit");
    private final static QName _TrTotWTax_QNAME = new QName("", "trTotWTax");
    private final static QName _TrTotTax_QNAME = new QName("", "trTotTax");
    private final static QName _COpenTime_QNAME = new QName("", "cOpenTime");
    private final static QName _TrlFuelDepst_QNAME = new QName("", "trlFuelDepst");
    private final static QName _TrlFeeDepNum_QNAME = new QName("", "trlFeeDepNum");
    private final static QName _TrlMatchNum_QNAME = new QName("", "trlMatchNum");
    private final static QName _TrGTotalizer_QNAME = new QName("", "trGTotalizer");
    private final static QName _TrlFeeDepName_QNAME = new QName("", "trlFeeDepName");
    private final static QName _OutsideSales_QNAME = new QName("", "outsideSales");
    private final static QName _TrSeq_QNAME = new QName("", "trSeq");
    private final static QName _TrFiscalTaxExemptInfo_QNAME = new QName("", "trFiscalTaxExemptInfo");
    private final static QName _TrlFeeAmount_QNAME = new QName("", "trlFeeAmount");
    private final static QName _InsideGrand_QNAME = new QName("", "insideGrand");
    private final static QName _TrlcblName_QNAME = new QName("", "trlcblName");
    private final static QName _BeginTicket_QNAME = new QName("", "beginTicket");
    private final static QName _TrlDesc_QNAME = new QName("", "trlDesc");
    private final static QName _TrlcbETime_QNAME = new QName("", "trlcbETime");
    private final static QName _TrlSellUnit_QNAME = new QName("", "trlSellUnit");
    private final static QName _TrlLineTot_QNAME = new QName("", "trlLineTot");
    private final static QName _NegTaxAmts_QNAME = new QName("", "negTaxAmts");
    private final static QName _TrlMatchName_QNAME = new QName("", "trlMatchName");
    private final static QName _TrFuelOnlyCst_QNAME = new QName("", "trFuelOnlyCst");
    private final static QName _TrlYQty_QNAME = new QName("", "trlYQty");
    private final static QName _TrlpdDiscProgramId_QNAME = new QName("", "trlpdDiscProgramId");
    private final static QName _Duration_QNAME = new QName("", "duration");
    private final static QName _CCloseTime_QNAME = new QName("", "cCloseTime");
    private final static QName _Cashier_QNAME = new QName("", "cashier");
    private final static QName _TrFuelDeposit_QNAME = new QName("", "trFuelDeposit");
    private final static QName _TrlcblUPC_QNAME = new QName("", "trlcblUPC");
    private final static QName _TrpAmt_QNAME = new QName("", "trpAmt");
    private final static QName _TrlpdAmount_QNAME = new QName("", "trlpdAmount");
    private final static QName _TrVendorPmt_QNAME = new QName("", "trVendorPmt");
    private final static QName _TrlUnitPrice_QNAME = new QName("", "trlUnitPrice");
    private final static QName _OverallSales_QNAME = new QName("", "overallSales");
    private final static QName _CustDOB_QNAME = new QName("", "custDOB");
    private final static QName _FuelVolume_QNAME = new QName("", "fuelVolume");
    private final static QName _PosNum_QNAME = new QName("", "posNum");
    private final static QName _CustPhoneNumber_QNAME = new QName("", "custPhoneNumber");
    private final static QName _ReconciledByName_QNAME = new QName("", "reconciledByName");
    private final static QName _TrTickNum_QNAME = new QName("", "trTickNum");
    private final static QName _TrlUPC_QNAME = new QName("", "trlUPC");
    private final static QName _TrlcblOPrice_QNAME = new QName("", "trlcblOPrice");
    private final static QName _CoinDispensed_QNAME = new QName("", "coinDispensed");
    private final static QName _TrlFeeNum_QNAME = new QName("", "trlFeeNum");
    private final static QName _TrSTotalizer_QNAME = new QName("", "trSTotalizer");
    private final static QName _RecallAmt_QNAME = new QName("", "recallAmt");
    private final static QName _TrlModifier_QNAME = new QName("", "trlModifier");
    private final static QName _TrJournalTrjDCash50_QNAME = new QName("", "trjDCash50");
    private final static QName _TrJournalTrjDInHouse_QNAME = new QName("", "trjDInHouse");
    private final static QName _TrJournalTrjDrTotals_QNAME = new QName("", "trjDrTotals");
    private final static QName _TrJournalTrjDPumpTest_QNAME = new QName("", "trjDPumpTest");
    private final static QName _TrJournalTrjDFoodStamp_QNAME = new QName("", "trjDFoodStamp");
    private final static QName _TrJournalTrjDCash10_QNAME = new QName("", "trjDCash10");
    private final static QName _TrJournalTrjDCoupon_QNAME = new QName("", "trjDCoupon");
    private final static QName _TrJournalTrjDVeriPass_QNAME = new QName("", "trjDVeriPass");
    private final static QName _TrJournalTrjDHonorAll_QNAME = new QName("", "trjDHonorAll");
    private final static QName _TrJournalTrjPrintCount_QNAME = new QName("", "trjPrintCount");
    private final static QName _TrJournalTrjDCheck_QNAME = new QName("", "trjDCheck");
    private final static QName _TrJournalTrDjElectrFS_QNAME = new QName("", "trDjElectrFS");
    private final static QName _TrJournalTrjDLotto_QNAME = new QName("", "trjDLotto");
    private final static QName _TrJournalTrjDCredit_QNAME = new QName("", "trjDCredit");
    private final static QName _TrJournalTrjDDriveOff_QNAME = new QName("", "trjDDriveOff");
    private final static QName _TrJournalTrjDCash1_QNAME = new QName("", "trjDCash1");
    private final static QName _TrJournalTrjPumpNumber_QNAME = new QName("", "trjPumpNumber");
    private final static QName _TrJournalTrjDCash_QNAME = new QName("", "trjDCash");
    private final static QName _TrJournalTrjDDebit_QNAME = new QName("", "trjDDebit");
    private final static QName _TrJournalTrjDManDeb_QNAME = new QName("", "trjDManDeb");
    private final static QName _TrJournalTrjDCash5_QNAME = new QName("", "trjDCash5");
    private final static QName _TrJournalTrjDCash20_QNAME = new QName("", "trjDCash20");
    private final static QName _TrJournalTrjDSpcDisc_QNAME = new QName("", "trjDSpcDisc");
    private final static QName _TrJournalTrjTicketNum_QNAME = new QName("", "trjTicketNum");
    private final static QName _TrJournalTrjDManCred_QNAME = new QName("", "trjDManCred");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.transset
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrLoyalty }
     * 
     */
    public TrLoyalty createTrLoyalty() {
        return new TrLoyalty();
    }

    /**
     * Create an instance of {@link TrCshBk }
     * 
     */
    public TrCshBk createTrCshBk() {
        return new TrCshBk();
    }

    /**
     * Create an instance of {@link TrPayline }
     * 
     */
    public TrPayline createTrPayline() {
        return new TrPayline();
    }

    /**
     * Create an instance of {@link TrpCardInfo }
     * 
     */
    public TrpCardInfo createTrpCardInfo() {
        return new TrpCardInfo();
    }

    /**
     * Create an instance of {@link TrlFlags }
     * 
     */
    public TrlFlags createTrlFlags() {
        return new TrlFlags();
    }

    /**
     * Create an instance of {@link TrlFuel }
     * 
     */
    public TrlFuel createTrlFuel() {
        return new TrlFuel();
    }

    /**
     * Create an instance of {@link TrlCw }
     * 
     */
    public TrlCw createTrlCw() {
        return new TrlCw();
    }

    /**
     * Create an instance of {@link TrLine }
     * 
     */
    public TrLine createTrLine() {
        return new TrLine();
    }

    /**
     * Create an instance of {@link TrMixMatches }
     * 
     */
    public TrMixMatches createTrMixMatches() {
        return new TrMixMatches();
    }

    /**
     * Create an instance of {@link TrJournal }
     * 
     */
    public TrJournal createTrJournal() {
        return new TrJournal();
    }

    /**
     * Create an instance of {@link TrFiscalReceiptInfo }
     * 
     */
    public TrFiscalReceiptInfo createTrFiscalReceiptInfo() {
        return new TrFiscalReceiptInfo();
    }

    /**
     * Create an instance of {@link TrExNetProds }
     * 
     */
    public TrExNetProds createTrExNetProds() {
        return new TrExNetProds();
    }

    /**
     * Create an instance of {@link Trans }
     * 
     */
    public Trans createTrans() {
        return new Trans();
    }

    /**
     * Create an instance of {@link TrJournal.TrjDrTotals }
     * 
     */
    public TrJournal.TrjDrTotals createTrJournalTrjDrTotals() {
        return new TrJournal.TrjDrTotals();
    }

    /**
     * Create an instance of {@link TrMixMatches.TrMixMatch }
     * 
     */
    public TrMixMatches.TrMixMatch createTrMixMatchesTrMixMatch() {
        return new TrMixMatches.TrMixMatch();
    }

    /**
     * Create an instance of {@link TrMixMatches.TrMixMatch.TrMMSalesLines }
     * 
     */
    public TrMixMatches.TrMixMatch.TrMMSalesLines createTrMixMatchesTrMixMatchTrMMSalesLines() {
        return new TrMixMatches.TrMixMatch.TrMMSalesLines();
    }

    /**
     * Create an instance of {@link PriceChangeInfoType }
     * 
     */
    public PriceChangeInfoType createPriceChangeInfoType() {
        return new PriceChangeInfoType();
    }

    /**
     * Create an instance of {@link TrLine.TrlAppSpcfcData }
     * 
     */
    public TrLine.TrlAppSpcfcData createTrLineTrlAppSpcfcData() {
        return new TrLine.TrlAppSpcfcData();
    }

    /**
     * Create an instance of {@link TrLine.TrlMixMatches }
     * 
     */
    public TrLine.TrlMixMatches createTrLineTrlMixMatches() {
        return new TrLine.TrlMixMatches();
    }

    /**
     * Create an instance of {@link TrLine.TrlMixMatches.TrlMatchLine }
     * 
     */
    public TrLine.TrlMixMatches.TrlMatchLine createTrLineTrlMixMatchesTrlMatchLine() {
        return new TrLine.TrlMixMatches.TrlMatchLine();
    }

    /**
     * Create an instance of {@link TrHeaderType }
     * 
     */
    public TrHeaderType createTrHeaderType() {
        return new TrHeaderType();
    }

    /**
     * Create an instance of {@link BaseCashierType }
     * 
     */
    public BaseCashierType createBaseCashierType() {
        return new BaseCashierType();
    }

    /**
     * Create an instance of {@link TrpSigCap }
     * 
     */
    public TrpSigCap createTrpSigCap() {
        return new TrpSigCap();
    }

    /**
     * Create an instance of {@link TrLoyalty.TrLoyaltyProgram }
     * 
     */
    public TrLoyalty.TrLoyaltyProgram createTrLoyaltyTrLoyaltyProgram() {
        return new TrLoyalty.TrLoyaltyProgram();
    }

    /**
     * Create an instance of {@link TrPaylines }
     * 
     */
    public TrPaylines createTrPaylines() {
        return new TrPaylines();
    }

    /**
     * Create an instance of {@link TrpPaycode }
     * 
     */
    public TrpPaycode createTrpPaycode() {
        return new TrpPaycode();
    }

    /**
     * Create an instance of {@link TrCshBk.TrCshBkAmt }
     * 
     */
    public TrCshBk.TrCshBkAmt createTrCshBkTrCshBkAmt() {
        return new TrCshBk.TrCshBkAmt();
    }

    /**
     * Create an instance of {@link TrpForeign }
     * 
     */
    public TrpForeign createTrpForeign() {
        return new TrpForeign();
    }

    /**
     * Create an instance of {@link TrPayline.TrpHouseAcct }
     * 
     */
    public TrPayline.TrpHouseAcct createTrPaylineTrpHouseAcct() {
        return new TrPayline.TrpHouseAcct();
    }

    /**
     * Create an instance of {@link TrpCardInfo.TrpcAccount }
     * 
     */
    public TrpCardInfo.TrpcAccount createTrpCardInfoTrpcAccount() {
        return new TrpCardInfo.TrpcAccount();
    }

    /**
     * Create an instance of {@link TrpCardInfo.TrpcCCName }
     * 
     */
    public TrpCardInfo.TrpcCCName createTrpCardInfoTrpcCCName() {
        return new TrpCardInfo.TrpcCCName();
    }

    /**
     * Create an instance of {@link TrpCardInfo.TrpcHostID }
     * 
     */
    public TrpCardInfo.TrpcHostID createTrpCardInfoTrpcHostID() {
        return new TrpCardInfo.TrpcHostID();
    }

    /**
     * Create an instance of {@link TrpCardInfo.TrpcMerchInfo }
     * 
     */
    public TrpCardInfo.TrpcMerchInfo createTrpCardInfoTrpcMerchInfo() {
        return new TrpCardInfo.TrpcMerchInfo();
    }

    /**
     * Create an instance of {@link TrpCardInfo.Extension }
     * 
     */
    public TrpCardInfo.Extension createTrpCardInfoExtension() {
        return new TrpCardInfo.Extension();
    }

    /**
     * Create an instance of {@link TrPayline.TrpAppSpcfcData }
     * 
     */
    public TrPayline.TrpAppSpcfcData createTrPaylineTrpAppSpcfcData() {
        return new TrPayline.TrpAppSpcfcData();
    }

    /**
     * Create an instance of {@link MwsMgrReviewEvent }
     * 
     */
    public MwsMgrReviewEvent createMwsMgrReviewEvent() {
        return new MwsMgrReviewEvent();
    }

    /**
     * Create an instance of {@link TrRecall }
     * 
     */
    public TrRecall createTrRecall() {
        return new TrRecall();
    }

    /**
     * Create an instance of {@link TrTickNum }
     * 
     */
    public TrTickNum createTrTickNum() {
        return new TrTickNum();
    }

    /**
     * Create an instance of {@link TrLines }
     * 
     */
    public TrLines createTrLines() {
        return new TrLines();
    }

    /**
     * Create an instance of {@link TrlTaxes }
     * 
     */
    public TrlTaxes createTrlTaxes() {
        return new TrlTaxes();
    }

    /**
     * Create an instance of {@link TrlTax }
     * 
     */
    public TrlTax createTrlTax() {
        return new TrlTax();
    }

    /**
     * Create an instance of {@link TrlRate }
     * 
     */
    public TrlRate createTrlRate() {
        return new TrlRate();
    }

    /**
     * Create an instance of {@link TrlFee }
     * 
     */
    public TrlFee createTrlFee() {
        return new TrlFee();
    }

    /**
     * Create an instance of {@link TrlFeeCat }
     * 
     */
    public TrlFeeCat createTrlFeeCat() {
        return new TrlFeeCat();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlNegative }
     * 
     */
    public TrlFlags.TrlNegative createTrlFlagsTrlNegative() {
        return new TrlFlags.TrlNegative();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlDeli }
     * 
     */
    public TrlFlags.TrlDeli createTrlFlagsTrlDeli() {
        return new TrlFlags.TrlDeli();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlBay }
     * 
     */
    public TrlFlags.TrlBay createTrlFlagsTrlBay() {
        return new TrlFlags.TrlBay();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlFstmp }
     * 
     */
    public TrlFlags.TrlFstmp createTrlFlagsTrlFstmp() {
        return new TrlFlags.TrlFstmp();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlSpDisc }
     * 
     */
    public TrlFlags.TrlSpDisc createTrlFlagsTrlSpDisc() {
        return new TrlFlags.TrlSpDisc();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlPrepdCard }
     * 
     */
    public TrlFlags.TrlPrepdCard createTrlFlagsTrlPrepdCard() {
        return new TrlFlags.TrlPrepdCard();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlBdayVerif }
     * 
     */
    public TrlFlags.TrlBdayVerif createTrlFlagsTrlBdayVerif() {
        return new TrlFlags.TrlBdayVerif();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlPLUNotFnd }
     * 
     */
    public TrlFlags.TrlPLUNotFnd createTrlFlagsTrlPLUNotFnd() {
        return new TrlFlags.TrlPLUNotFnd();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlPLUNotScan }
     * 
     */
    public TrlFlags.TrlPLUNotScan createTrlFlagsTrlPLUNotScan() {
        return new TrlFlags.TrlPLUNotScan();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlPLU }
     * 
     */
    public TrlFlags.TrlPLU createTrlFlagsTrlPLU() {
        return new TrlFlags.TrlPLU();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlMoneyOrder }
     * 
     */
    public TrlFlags.TrlMoneyOrder createTrlFlagsTrlMoneyOrder() {
        return new TrlFlags.TrlMoneyOrder();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlUpdPluCust }
     * 
     */
    public TrlFlags.TrlUpdPluCust createTrlFlagsTrlUpdPluCust() {
        return new TrlFlags.TrlUpdPluCust();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlUpdDepCust }
     * 
     */
    public TrlFlags.TrlUpdDepCust createTrlFlagsTrlUpdDepCust() {
        return new TrlFlags.TrlUpdDepCust();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlNetVoid }
     * 
     */
    public TrlFlags.TrlNetVoid createTrlFlagsTrlNetVoid() {
        return new TrlFlags.TrlNetVoid();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlCatCust }
     * 
     */
    public TrlFlags.TrlCatCust createTrlFlagsTrlCatCust() {
        return new TrlFlags.TrlCatCust();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlFuelOnly }
     * 
     */
    public TrlFlags.TrlFuelOnly createTrlFlagsTrlFuelOnly() {
        return new TrlFlags.TrlFuelOnly();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlFuelSale }
     * 
     */
    public TrlFlags.TrlFuelSale createTrlFlagsTrlFuelSale() {
        return new TrlFlags.TrlFuelSale();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlPriceOvrd }
     * 
     */
    public TrlFlags.TrlPriceOvrd createTrlFlagsTrlPriceOvrd() {
        return new TrlFlags.TrlPriceOvrd();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlFirstCAB }
     * 
     */
    public TrlFlags.TrlFirstCAB createTrlFlagsTrlFirstCAB() {
        return new TrlFlags.TrlFirstCAB();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlMatch }
     * 
     */
    public TrlFlags.TrlMatch createTrlFlagsTrlMatch() {
        return new TrlFlags.TrlMatch();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlPopMemDCR }
     * 
     */
    public TrlFlags.TrlPopMemDCR createTrlFlagsTrlPopMemDCR() {
        return new TrlFlags.TrlPopMemDCR();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlCWDoPromo }
     * 
     */
    public TrlFlags.TrlCWDoPromo createTrlFlagsTrlCWDoPromo() {
        return new TrlFlags.TrlCWDoPromo();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlCWPromoDn }
     * 
     */
    public TrlFlags.TrlCWPromoDn createTrlFlagsTrlCWPromoDn() {
        return new TrlFlags.TrlCWPromoDn();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlCouponRedeemed }
     * 
     */
    public TrlFlags.TrlCouponRedeemed createTrlFlagsTrlCouponRedeemed() {
        return new TrlFlags.TrlCouponRedeemed();
    }

    /**
     * Create an instance of {@link TrlFlags.TrlLoyLnDisc }
     * 
     */
    public TrlFlags.TrlLoyLnDisc createTrlFlagsTrlLoyLnDisc() {
        return new TrlFlags.TrlLoyLnDisc();
    }

    /**
     * Create an instance of {@link TaxableRebate }
     * 
     */
    public TaxableRebate createTaxableRebate() {
        return new TaxableRebate();
    }

    /**
     * Create an instance of {@link TrlDept }
     * 
     */
    public TrlDept createTrlDept() {
        return new TrlDept();
    }

    /**
     * Create an instance of {@link TrlCat }
     * 
     */
    public TrlCat createTrlCat() {
        return new TrlCat();
    }

    /**
     * Create an instance of {@link TrlDisc }
     * 
     */
    public TrlDisc createTrlDisc() {
        return new TrlDisc();
    }

    /**
     * Create an instance of {@link TrlPromo }
     * 
     */
    public TrlPromo createTrlPromo() {
        return new TrlPromo();
    }

    /**
     * Create an instance of {@link OvrdCshrType }
     * 
     */
    public OvrdCshrType createOvrdCshrType() {
        return new OvrdCshrType();
    }

    /**
     * Create an instance of {@link FuelProd }
     * 
     */
    public FuelProd createFuelProd() {
        return new FuelProd();
    }

    /**
     * Create an instance of {@link FuelSvcMode }
     * 
     */
    public FuelSvcMode createFuelSvcMode() {
        return new FuelSvcMode();
    }

    /**
     * Create an instance of {@link FuelMOP }
     * 
     */
    public FuelMOP createFuelMOP() {
        return new FuelMOP();
    }

    /**
     * Create an instance of {@link FuelTaxInfoType }
     * 
     */
    public FuelTaxInfoType createFuelTaxInfoType() {
        return new FuelTaxInfoType();
    }

    /**
     * Create an instance of {@link TrlFuel.TrlFiscalFlatTax }
     * 
     */
    public TrlFuel.TrlFiscalFlatTax createTrlFuelTrlFiscalFlatTax() {
        return new TrlFuel.TrlFiscalFlatTax();
    }

    /**
     * Create an instance of {@link TrlFuel.FuelOverrun }
     * 
     */
    public TrlFuel.FuelOverrun createTrlFuelFuelOverrun() {
        return new TrlFuel.FuelOverrun();
    }

    /**
     * Create an instance of {@link TrlUPCEntry }
     * 
     */
    public TrlUPCEntry createTrlUPCEntry() {
        return new TrlUPCEntry();
    }

    /**
     * Create an instance of {@link TrlMO }
     * 
     */
    public TrlMO createTrlMO() {
        return new TrlMO();
    }

    /**
     * Create an instance of {@link TrlCw.TrlCwPromo }
     * 
     */
    public TrlCw.TrlCwPromo createTrlCwTrlCwPromo() {
        return new TrlCw.TrlCwPromo();
    }

    /**
     * Create an instance of {@link TrlCombo }
     * 
     */
    public TrlCombo createTrlCombo() {
        return new TrlCombo();
    }

    /**
     * Create an instance of {@link TrlcbLine }
     * 
     */
    public TrlcbLine createTrlcbLine() {
        return new TrlcbLine();
    }

    /**
     * Create an instance of {@link TrlcblDept }
     * 
     */
    public TrlcblDept createTrlcblDept() {
        return new TrlcblDept();
    }

    /**
     * Create an instance of {@link TrlcblCat }
     * 
     */
    public TrlcblCat createTrlcblCat() {
        return new TrlcblCat();
    }

    /**
     * Create an instance of {@link com.transset.TrlMatch }
     * 
     */
    public com.transset.TrlMatch createTrlMatch() {
        return new com.transset.TrlMatch();
    }

    /**
     * Create an instance of {@link TrlPopDisc }
     * 
     */
    public TrlPopDisc createTrlPopDisc() {
        return new TrlPopDisc();
    }

    /**
     * Create an instance of {@link TrlpdTime }
     * 
     */
    public TrlpdTime createTrlpdTime() {
        return new TrlpdTime();
    }

    /**
     * Create an instance of {@link TrlpdMatch }
     * 
     */
    public TrlpdMatch createTrlpdMatch() {
        return new TrlpdMatch();
    }

    /**
     * Create an instance of {@link TrlpdMemEMeth }
     * 
     */
    public TrlpdMemEMeth createTrlpdMemEMeth() {
        return new TrlpdMemEMeth();
    }

    /**
     * Create an instance of {@link CouponDiscountType }
     * 
     */
    public CouponDiscountType createCouponDiscountType() {
        return new CouponDiscountType();
    }

    /**
     * Create an instance of {@link TrLine.TrloLnItemDisc }
     * 
     */
    public TrLine.TrloLnItemDisc createTrLineTrloLnItemDisc() {
        return new TrLine.TrloLnItemDisc();
    }

    /**
     * Create an instance of {@link TrLine.TrloPPGDisc }
     * 
     */
    public TrLine.TrloPPGDisc createTrLineTrloPPGDisc() {
        return new TrLine.TrloPPGDisc();
    }

    /**
     * Create an instance of {@link DepositAmount }
     * 
     */
    public DepositAmount createDepositAmount() {
        return new DepositAmount();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link TrPriceChange }
     * 
     */
    public TrPriceChange createTrPriceChange() {
        return new TrPriceChange();
    }

    /**
     * Create an instance of {@link MwsMgrCorrectionEvent }
     * 
     */
    public MwsMgrCorrectionEvent createMwsMgrCorrectionEvent() {
        return new MwsMgrCorrectionEvent();
    }

    /**
     * Create an instance of {@link CashierType }
     * 
     */
    public CashierType createCashierType() {
        return new CashierType();
    }

    /**
     * Create an instance of {@link CorrectionType }
     * 
     */
    public CorrectionType createCorrectionType() {
        return new CorrectionType();
    }

    /**
     * Create an instance of {@link TrHouseAcct }
     * 
     */
    public TrHouseAcct createTrHouseAcct() {
        return new TrHouseAcct();
    }

    /**
     * Create an instance of {@link EndTotals }
     * 
     */
    public EndTotals createEndTotals() {
        return new EndTotals();
    }

    /**
     * Create an instance of {@link TrlTaxex }
     * 
     */
    public TrlTaxex createTrlTaxex() {
        return new TrlTaxex();
    }

    /**
     * Create an instance of {@link PrintCashier }
     * 
     */
    public PrintCashier createPrintCashier() {
        return new PrintCashier();
    }

    /**
     * Create an instance of {@link DrawerAmounts }
     * 
     */
    public DrawerAmounts createDrawerAmounts() {
        return new DrawerAmounts();
    }

    /**
     * Create an instance of {@link DrawerAmount }
     * 
     */
    public DrawerAmount createDrawerAmount() {
        return new DrawerAmount();
    }

    /**
     * Create an instance of {@link PaymentName }
     * 
     */
    public PaymentName createPaymentName() {
        return new PaymentName();
    }

    /**
     * Create an instance of {@link ECRAmount }
     * 
     */
    public ECRAmount createECRAmount() {
        return new ECRAmount();
    }

    /**
     * Create an instance of {@link ActualAmount }
     * 
     */
    public ActualAmount createActualAmount() {
        return new ActualAmount();
    }

    /**
     * Create an instance of {@link TrJournal.TrjText }
     * 
     */
    public TrJournal.TrjText createTrJournalTrjText() {
        return new TrJournal.TrjText();
    }

    /**
     * Create an instance of {@link TrJournal.PpdFunction }
     * 
     */
    public TrJournal.PpdFunction createTrJournalPpdFunction() {
        return new TrJournal.PpdFunction();
    }

    /**
     * Create an instance of {@link TrJournal.PriceCheckCancelItem }
     * 
     */
    public TrJournal.PriceCheckCancelItem createTrJournalPriceCheckCancelItem() {
        return new TrJournal.PriceCheckCancelItem();
    }

    /**
     * Create an instance of {@link TrJournal.Marker }
     * 
     */
    public TrJournal.Marker createTrJournalMarker() {
        return new TrJournal.Marker();
    }

    /**
     * Create an instance of {@link TrCwsh }
     * 
     */
    public TrCwsh createTrCwsh() {
        return new TrCwsh();
    }

    /**
     * Create an instance of {@link TrClock }
     * 
     */
    public TrClock createTrClock() {
        return new TrClock();
    }

    /**
     * Create an instance of {@link TrValue }
     * 
     */
    public TrValue createTrValue() {
        return new TrValue();
    }

    /**
     * Create an instance of {@link TrTax }
     * 
     */
    public TrTax createTrTax() {
        return new TrTax();
    }

    /**
     * Create an instance of {@link TaxAmts }
     * 
     */
    public TaxAmts createTaxAmts() {
        return new TaxAmts();
    }

    /**
     * Create an instance of {@link TrCurrTot }
     * 
     */
    public TrCurrTot createTrCurrTot() {
        return new TrCurrTot();
    }

    /**
     * Create an instance of {@link TrFstmp }
     * 
     */
    public TrFstmp createTrFstmp() {
        return new TrFstmp();
    }

    /**
     * Create an instance of {@link TrSpDisc }
     * 
     */
    public TrSpDisc createTrSpDisc() {
        return new TrSpDisc();
    }

    /**
     * Create an instance of {@link CustDOBCType }
     * 
     */
    public CustDOBCType createCustDOBCType() {
        return new CustDOBCType();
    }

    /**
     * Create an instance of {@link TrFiscalReceiptInfo.ReceiptNumber }
     * 
     */
    public TrFiscalReceiptInfo.ReceiptNumber createTrFiscalReceiptInfoReceiptNumber() {
        return new TrFiscalReceiptInfo.ReceiptNumber();
    }

    /**
     * Create an instance of {@link FiscalTaxExemptType }
     * 
     */
    public FiscalTaxExemptType createFiscalTaxExemptType() {
        return new FiscalTaxExemptType();
    }

    /**
     * Create an instance of {@link TrExNetProds.TrExNetProd }
     * 
     */
    public TrExNetProds.TrExNetProd createTrExNetProdsTrExNetProd() {
        return new TrExNetProds.TrExNetProd();
    }

    /**
     * Create an instance of {@link BeginCash }
     * 
     */
    public BeginCash createBeginCash() {
        return new BeginCash();
    }

    /**
     * Create an instance of {@link BeginFoodStmp }
     * 
     */
    public BeginFoodStmp createBeginFoodStmp() {
        return new BeginFoodStmp();
    }

    /**
     * Create an instance of {@link Trans.AppSpcfcData }
     * 
     */
    public Trans.AppSpcfcData createTransAppSpcfcData() {
        return new Trans.AppSpcfcData();
    }

    /**
     * Create an instance of {@link TrScannedCouponType }
     * 
     */
    public TrScannedCouponType createTrScannedCouponType() {
        return new TrScannedCouponType();
    }

    /**
     * Create an instance of {@link OpenCashier }
     * 
     */
    public OpenCashier createOpenCashier() {
        return new OpenCashier();
    }

    /**
     * Create an instance of {@link TermMsgSN }
     * 
     */
    public TermMsgSN createTermMsgSN() {
        return new TermMsgSN();
    }

    /**
     * Create an instance of {@link MwsMgrAcceptedEvent }
     * 
     */
    public MwsMgrAcceptedEvent createMwsMgrAcceptedEvent() {
        return new MwsMgrAcceptedEvent();
    }

    /**
     * Create an instance of {@link TaxInTot }
     * 
     */
    public TaxInTot createTaxInTot() {
        return new TaxInTot();
    }

    /**
     * Create an instance of {@link TaxForgiven }
     * 
     */
    public TaxForgiven createTaxForgiven() {
        return new TaxForgiven();
    }

    /**
     * Create an instance of {@link CloseCashier }
     * 
     */
    public CloseCashier createCloseCashier() {
        return new CloseCashier();
    }

    /**
     * Create an instance of {@link TaxForgivenAgainst }
     * 
     */
    public TaxForgivenAgainst createTaxForgivenAgainst() {
        return new TaxForgivenAgainst();
    }

    /**
     * Create an instance of {@link MwsMgrAdjustmentEvent }
     * 
     */
    public MwsMgrAdjustmentEvent createMwsMgrAdjustmentEvent() {
        return new MwsMgrAdjustmentEvent();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link OriginalSafeDropInfo }
     * 
     */
    public OriginalSafeDropInfo createOriginalSafeDropInfo() {
        return new OriginalSafeDropInfo();
    }

    /**
     * Create an instance of {@link TaxNet }
     * 
     */
    public TaxNet createTaxNet() {
        return new TaxNet();
    }

    /**
     * Create an instance of {@link com.transset.TrlPLUNotFnd }
     * 
     */
    public com.transset.TrlPLUNotFnd createTrlPLUNotFnd() {
        return new com.transset.TrlPLUNotFnd();
    }

    /**
     * Create an instance of {@link StartTotals }
     * 
     */
    public StartTotals createStartTotals() {
        return new StartTotals();
    }

    /**
     * Create an instance of {@link MwsMgrVerifiedCsrPds }
     * 
     */
    public MwsMgrVerifiedCsrPds createMwsMgrVerifiedCsrPds() {
        return new MwsMgrVerifiedCsrPds();
    }

    /**
     * Create an instance of {@link com.transset.TrlBdayVerif }
     * 
     */
    public com.transset.TrlBdayVerif createTrlBdayVerif() {
        return new com.transset.TrlBdayVerif();
    }

    /**
     * Create an instance of {@link TaxAmt }
     * 
     */
    public TaxAmt createTaxAmt() {
        return new TaxAmt();
    }

    /**
     * Create an instance of {@link TaxExempt }
     * 
     */
    public TaxExempt createTaxExempt() {
        return new TaxExempt();
    }

    /**
     * Create an instance of {@link MwsMgrFinalizeEvent }
     * 
     */
    public MwsMgrFinalizeEvent createMwsMgrFinalizeEvent() {
        return new MwsMgrFinalizeEvent();
    }

    /**
     * Create an instance of {@link TaxRate }
     * 
     */
    public TaxRate createTaxRate() {
        return new TaxRate();
    }

    /**
     * Create an instance of {@link TransSet }
     * 
     */
    public TransSet createTransSet() {
        return new TransSet();
    }

    /**
     * Create an instance of {@link TransList }
     * 
     */
    public TransList createTransList() {
        return new TransList();
    }

    /**
     * Create an instance of {@link TransNumList }
     * 
     */
    public TransNumList createTransNumList() {
        return new TransNumList();
    }

    /**
     * Create an instance of {@link FuelTier }
     * 
     */
    public FuelTier createFuelTier() {
        return new FuelTier();
    }

    /**
     * Create an instance of {@link TaxExemptAgainst }
     * 
     */
    public TaxExemptAgainst createTaxExemptAgainst() {
        return new TaxExemptAgainst();
    }

    /**
     * Create an instance of {@link com.transset.TrlFstmp }
     * 
     */
    public com.transset.TrlFstmp createTrlFstmp() {
        return new com.transset.TrlFstmp();
    }

    /**
     * Create an instance of {@link com.transset.TrlNegative }
     * 
     */
    public com.transset.TrlNegative createTrlNegative() {
        return new com.transset.TrlNegative();
    }

    /**
     * Create an instance of {@link TaxAttribute }
     * 
     */
    public TaxAttribute createTaxAttribute() {
        return new TaxAttribute();
    }

    /**
     * Create an instance of {@link PopCodeAutoGenType }
     * 
     */
    public PopCodeAutoGenType createPopCodeAutoGenType() {
        return new PopCodeAutoGenType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link PopCodesType }
     * 
     */
    public PopCodesType createPopCodesType() {
        return new PopCodesType();
    }

    /**
     * Create an instance of {@link TrJournal.TrjDrTotals.TrjdrTotal }
     * 
     */
    public TrJournal.TrjDrTotals.TrjdrTotal createTrJournalTrjDrTotalsTrjdrTotal() {
        return new TrJournal.TrjDrTotals.TrjdrTotal();
    }

    /**
     * Create an instance of {@link TrMixMatches.TrMixMatch.TrMMSalesLines.TrMMSalesLine }
     * 
     */
    public TrMixMatches.TrMixMatch.TrMMSalesLines.TrMMSalesLine createTrMixMatchesTrMixMatchTrMMSalesLinesTrMMSalesLine() {
        return new TrMixMatches.TrMixMatch.TrMMSalesLines.TrMMSalesLine();
    }

    /**
     * Create an instance of {@link PriceChangeInfoType.PreviousPrice }
     * 
     */
    public PriceChangeInfoType.PreviousPrice createPriceChangeInfoTypePreviousPrice() {
        return new PriceChangeInfoType.PreviousPrice();
    }

    /**
     * Create an instance of {@link PriceChangeInfoType.CurrentPrice }
     * 
     */
    public PriceChangeInfoType.CurrentPrice createPriceChangeInfoTypeCurrentPrice() {
        return new PriceChangeInfoType.CurrentPrice();
    }

    /**
     * Create an instance of {@link TrLine.TrlAppSpcfcData.TrlShellLoyalty }
     * 
     */
    public TrLine.TrlAppSpcfcData.TrlShellLoyalty createTrLineTrlAppSpcfcDataTrlShellLoyalty() {
        return new TrLine.TrlAppSpcfcData.TrlShellLoyalty();
    }

    /**
     * Create an instance of {@link TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionID }
     * 
     */
    public TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionID createTrLineTrlMixMatchesTrlMatchLineTrlPromotionID() {
        return new TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionID();
    }

    /**
     * Create an instance of {@link TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionItemListID }
     * 
     */
    public TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionItemListID createTrLineTrlMixMatchesTrlMatchLineTrlPromotionItemListID() {
        return new TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionItemListID();
    }

    /**
     * Create an instance of {@link TrHeaderType.ESafeId }
     * 
     */
    public TrHeaderType.ESafeId createTrHeaderTypeESafeId() {
        return new TrHeaderType.ESafeId();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseCashierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "originalCashier")
    public JAXBElement<BaseCashierType> createOriginalCashier(BaseCashierType value) {
        return new JAXBElement<BaseCashierType>(_OriginalCashier_QNAME, BaseCashierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcblCwCd")
    public JAXBElement<BigInteger> createTrlcblCwCd(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlcblCwCd_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlVoidLineIx")
    public JAXBElement<BigInteger> createTrlVoidLineIx(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlVoidLineIx_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "storeNumber")
    public JAXBElement<String> createStoreNumber(String value) {
        return new JAXBElement<String>(_StoreNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trTotNoTax")
    public JAXBElement<BigDecimal> createTrTotNoTax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrTotNoTax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trPrePayComp")
    public JAXBElement<String> createTrPrePayComp(String value) {
        return new JAXBElement<String>(_TrPrePayComp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlInvItemId")
    public JAXBElement<String> createTrlInvItemId(String value) {
        return new JAXBElement<String>(_TrlInvItemId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "insideSales")
    public JAXBElement<BigDecimal> createInsideSales(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_InsideSales_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "closedTime")
    public JAXBElement<XMLGregorianCalendar> createClosedTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ClosedTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcbBTime")
    public JAXBElement<XMLGregorianCalendar> createTrlcbBTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TrlcbBTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlNetwCode")
    public JAXBElement<BigInteger> createTrlNetwCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlNetwCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlXQty")
    public JAXBElement<BigDecimal> createTrlXQty(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlXQty_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlFeeIdentifier")
    public JAXBElement<String> createTrlFeeIdentifier(String value) {
        return new JAXBElement<String>(_TrlFeeIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcbPrice")
    public JAXBElement<BigDecimal> createTrlcbPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlcbPrice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcbNumber")
    public JAXBElement<BigInteger> createTrlcbNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlcbNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cashierPeriod")
    public JAXBElement<BigInteger> createCashierPeriod(BigInteger value) {
        return new JAXBElement<BigInteger>(_CashierPeriod_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trClockOut")
    public JAXBElement<XMLGregorianCalendar> createTrClockOut(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TrClockOut_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlFuelSeq")
    public JAXBElement<BigInteger> createTrlFuelSeq(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlFuelSeq_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcblModfr")
    public JAXBElement<BigInteger> createTrlcblModfr(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlcblModfr_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "outsideGrand")
    public JAXBElement<BigDecimal> createOutsideGrand(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_OutsideGrand_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcblAmt")
    public JAXBElement<BigDecimal> createTrlcblAmt(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlcblAmt_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "endTicket")
    public JAXBElement<BigInteger> createEndTicket(BigInteger value) {
        return new JAXBElement<BigInteger>(_EndTicket_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlMOPayee")
    public JAXBElement<String> createTrlMOPayee(String value) {
        return new JAXBElement<String>(_TrlMOPayee_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "popDiscTran")
    public JAXBElement<Object> createPopDiscTran(Object value) {
        return new JAXBElement<Object>(_PopDiscTran_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlQty")
    public JAXBElement<BigDecimal> createTrlQty(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlQty_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trMiscRefNum")
    public JAXBElement<String> createTrMiscRefNum(String value) {
        return new JAXBElement<String>(_TrMiscRefNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcblQty")
    public JAXBElement<BigDecimal> createTrlcblQty(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlcblQty_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcbPcode")
    public JAXBElement<BigInteger> createTrlcbPcode(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlcbPcode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "popCodeUsed")
    public JAXBElement<String> createPopCodeUsed(String value) {
        return new JAXBElement<String>(_PopCodeUsed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcblPrice")
    public JAXBElement<BigDecimal> createTrlcblPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlcblPrice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "openedTime")
    public JAXBElement<XMLGregorianCalendar> createOpenedTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OpenedTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlpdDescrip")
    public JAXBElement<String> createTrlpdDescrip(String value) {
        return new JAXBElement<String>(_TrlpdDescrip_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlpdGradeName")
    public JAXBElement<String> createTrlpdGradeName(String value) {
        return new JAXBElement<String>(_TrlpdGradeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcbDesc")
    public JAXBElement<String> createTrlcbDesc(String value) {
        return new JAXBElement<String>(_TrlcbDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlFeeName")
    public JAXBElement<String> createTrlFeeName(String value) {
        return new JAXBElement<String>(_TrlFeeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ticketCount")
    public JAXBElement<Object> createTicketCount(Object value) {
        return new JAXBElement<Object>(_TicketCount_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxAmts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "taxAmts")
    public JAXBElement<TaxAmts> createTaxAmts(TaxAmts value) {
        return new JAXBElement<TaxAmts>(_TaxAmts_QNAME, TaxAmts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reconciledByID")
    public JAXBElement<BigInteger> createReconciledByID(BigInteger value) {
        return new JAXBElement<BigInteger>(_ReconciledByID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trClockIn")
    public JAXBElement<XMLGregorianCalendar> createTrClockIn(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TrClockIn_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fuelPosition")
    public JAXBElement<Integer> createFuelPosition(Integer value) {
        return new JAXBElement<Integer>(_FuelPosition_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "custName")
    public JAXBElement<String> createCustName(String value) {
        return new JAXBElement<String>(_CustName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlSerialNum")
    public JAXBElement<String> createTrlSerialNum(String value) {
        return new JAXBElement<String>(_TrlSerialNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlpdFuelDef")
    public JAXBElement<BigInteger> createTrlpdFuelDef(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlpdFuelDef_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mwsEnabled")
    public JAXBElement<BigInteger> createMwsEnabled(BigInteger value) {
        return new JAXBElement<BigInteger>(_MwsEnabled_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlpdCodeUsed")
    public JAXBElement<String> createTrlpdCodeUsed(String value) {
        return new JAXBElement<String>(_TrlpdCodeUsed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrTickNum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trOriginalTickNum")
    public JAXBElement<TrTickNum> createTrOriginalTickNum(TrTickNum value) {
        return new JAXBElement<TrTickNum>(_TrOriginalTickNum_QNAME, TrTickNum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlSign")
    public JAXBElement<BigDecimal> createTrlSign(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlSign_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "overallGrand")
    public JAXBElement<BigDecimal> createOverallGrand(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_OverallGrand_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlpdMemberID")
    public JAXBElement<String> createTrlpdMemberID(String value) {
        return new JAXBElement<String>(_TrlpdMemberID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date")
    public JAXBElement<XMLGregorianCalendar> createDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Date_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trHeader")
    public JAXBElement<TrHeaderType> createTrHeader(TrHeaderType value) {
        return new JAXBElement<TrHeaderType>(_TrHeader_QNAME, TrHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "till")
    public JAXBElement<Integer> createTill(Integer value) {
        return new JAXBElement<Integer>(_Till_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlpdPGUnit")
    public JAXBElement<BigDecimal> createTrlpdPGUnit(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlpdPGUnit_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trTotWTax")
    public JAXBElement<BigDecimal> createTrTotWTax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrTotWTax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trTotTax")
    public JAXBElement<BigDecimal> createTrTotTax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrTotTax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cOpenTime")
    public JAXBElement<XMLGregorianCalendar> createCOpenTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_COpenTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlFuelDepst")
    public JAXBElement<BigDecimal> createTrlFuelDepst(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlFuelDepst_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlFeeDepNum")
    public JAXBElement<BigInteger> createTrlFeeDepNum(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlFeeDepNum_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlMatchNum")
    public JAXBElement<BigInteger> createTrlMatchNum(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlMatchNum_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trGTotalizer")
    public JAXBElement<BigDecimal> createTrGTotalizer(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrGTotalizer_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlFeeDepName")
    public JAXBElement<String> createTrlFeeDepName(String value) {
        return new JAXBElement<String>(_TrlFeeDepName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "outsideSales")
    public JAXBElement<BigDecimal> createOutsideSales(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_OutsideSales_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trSeq")
    public JAXBElement<BigInteger> createTrSeq(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrSeq_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FiscalTaxExemptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trFiscalTaxExemptInfo")
    public JAXBElement<FiscalTaxExemptType> createTrFiscalTaxExemptInfo(FiscalTaxExemptType value) {
        return new JAXBElement<FiscalTaxExemptType>(_TrFiscalTaxExemptInfo_QNAME, FiscalTaxExemptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlFeeAmount")
    public JAXBElement<BigDecimal> createTrlFeeAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlFeeAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "insideGrand")
    public JAXBElement<BigDecimal> createInsideGrand(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_InsideGrand_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcblName")
    public JAXBElement<String> createTrlcblName(String value) {
        return new JAXBElement<String>(_TrlcblName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beginTicket")
    public JAXBElement<BigInteger> createBeginTicket(BigInteger value) {
        return new JAXBElement<BigInteger>(_BeginTicket_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlDesc")
    public JAXBElement<String> createTrlDesc(String value) {
        return new JAXBElement<String>(_TrlDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcbETime")
    public JAXBElement<XMLGregorianCalendar> createTrlcbETime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TrlcbETime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlSellUnit")
    public JAXBElement<BigDecimal> createTrlSellUnit(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlSellUnit_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlLineTot")
    public JAXBElement<BigDecimal> createTrlLineTot(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlLineTot_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxAmts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "negTaxAmts")
    public JAXBElement<TaxAmts> createNegTaxAmts(TaxAmts value) {
        return new JAXBElement<TaxAmts>(_NegTaxAmts_QNAME, TaxAmts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlMatchName")
    public JAXBElement<String> createTrlMatchName(String value) {
        return new JAXBElement<String>(_TrlMatchName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trFuelOnlyCst")
    public JAXBElement<String> createTrFuelOnlyCst(String value) {
        return new JAXBElement<String>(_TrFuelOnlyCst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlYQty")
    public JAXBElement<BigDecimal> createTrlYQty(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlYQty_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlpdDiscProgramId")
    public JAXBElement<BigInteger> createTrlpdDiscProgramId(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlpdDiscProgramId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "duration")
    public JAXBElement<BigInteger> createDuration(BigInteger value) {
        return new JAXBElement<BigInteger>(_Duration_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cCloseTime")
    public JAXBElement<XMLGregorianCalendar> createCCloseTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CCloseTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseCashierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cashier")
    public JAXBElement<BaseCashierType> createCashier(BaseCashierType value) {
        return new JAXBElement<BaseCashierType>(_Cashier_QNAME, BaseCashierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trFuelDeposit")
    public JAXBElement<String> createTrFuelDeposit(String value) {
        return new JAXBElement<String>(_TrFuelDeposit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcblUPC")
    public JAXBElement<String> createTrlcblUPC(String value) {
        return new JAXBElement<String>(_TrlcblUPC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trpAmt")
    public JAXBElement<BigDecimal> createTrpAmt(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrpAmt_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlpdAmount")
    public JAXBElement<BigDecimal> createTrlpdAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlpdAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trVendorPmt")
    public JAXBElement<String> createTrVendorPmt(String value) {
        return new JAXBElement<String>(_TrVendorPmt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlUnitPrice")
    public JAXBElement<BigDecimal> createTrlUnitPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlUnitPrice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "overallSales")
    public JAXBElement<BigDecimal> createOverallSales(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_OverallSales_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustDOBCType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "custDOB")
    public JAXBElement<CustDOBCType> createCustDOB(CustDOBCType value) {
        return new JAXBElement<CustDOBCType>(_CustDOB_QNAME, CustDOBCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fuelVolume")
    public JAXBElement<BigDecimal> createFuelVolume(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_FuelVolume_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "posNum")
    public JAXBElement<BigInteger> createPosNum(BigInteger value) {
        return new JAXBElement<BigInteger>(_PosNum_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "custPhoneNumber")
    public JAXBElement<String> createCustPhoneNumber(String value) {
        return new JAXBElement<String>(_CustPhoneNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reconciledByName")
    public JAXBElement<String> createReconciledByName(String value) {
        return new JAXBElement<String>(_ReconciledByName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrTickNum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trTickNum")
    public JAXBElement<TrTickNum> createTrTickNum(TrTickNum value) {
        return new JAXBElement<TrTickNum>(_TrTickNum_QNAME, TrTickNum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlUPC")
    public JAXBElement<String> createTrlUPC(String value) {
        return new JAXBElement<String>(_TrlUPC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlcblOPrice")
    public JAXBElement<BigDecimal> createTrlcblOPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrlcblOPrice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "coinDispensed")
    public JAXBElement<BigDecimal> createCoinDispensed(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CoinDispensed_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlFeeNum")
    public JAXBElement<BigInteger> createTrlFeeNum(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlFeeNum_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trSTotalizer")
    public JAXBElement<BigDecimal> createTrSTotalizer(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrSTotalizer_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "recallAmt")
    public JAXBElement<BigDecimal> createRecallAmt(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RecallAmt_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trlModifier")
    public JAXBElement<BigInteger> createTrlModifier(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrlModifier_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDCash50", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDCash50(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDCash50_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDInHouse", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDInHouse(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDInHouse_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrJournal.TrjDrTotals }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDrTotals", scope = TrJournal.class)
    public JAXBElement<TrJournal.TrjDrTotals> createTrJournalTrjDrTotals(TrJournal.TrjDrTotals value) {
        return new JAXBElement<TrJournal.TrjDrTotals>(_TrJournalTrjDrTotals_QNAME, TrJournal.TrjDrTotals.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDPumpTest", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDPumpTest(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDPumpTest_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDFoodStamp", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDFoodStamp(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDFoodStamp_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDCash10", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDCash10(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDCash10_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDCoupon", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDCoupon(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDCoupon_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDVeriPass", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDVeriPass(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDVeriPass_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDHonorAll", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDHonorAll(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDHonorAll_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjPrintCount", scope = TrJournal.class)
    public JAXBElement<BigInteger> createTrJournalTrjPrintCount(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrJournalTrjPrintCount_QNAME, BigInteger.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDCheck", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDCheck(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDCheck_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trDjElectrFS", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrDjElectrFS(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrDjElectrFS_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDLotto", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDLotto(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDLotto_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDCredit", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDCredit(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDCredit_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDDriveOff", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDDriveOff(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDDriveOff_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDCash1", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDCash1(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDCash1_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjPumpNumber", scope = TrJournal.class)
    public JAXBElement<BigInteger> createTrJournalTrjPumpNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrJournalTrjPumpNumber_QNAME, BigInteger.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDCash", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDCash(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDCash_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDDebit", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDDebit(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDDebit_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDManDeb", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDManDeb(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDManDeb_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDCash5", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDCash5(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDCash5_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDCash20", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDCash20(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDCash20_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDSpcDisc", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDSpcDisc(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDSpcDisc_QNAME, BigDecimal.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjTicketNum", scope = TrJournal.class)
    public JAXBElement<BigInteger> createTrJournalTrjTicketNum(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrJournalTrjTicketNum_QNAME, BigInteger.class, TrJournal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trjDManCred", scope = TrJournal.class)
    public JAXBElement<BigDecimal> createTrJournalTrjDManCred(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TrJournalTrjDManCred_QNAME, BigDecimal.class, TrJournal.class, value);
    }

}
