//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}cashier"/>
 *         &lt;element ref="{}posNum"/>
 *         &lt;element ref="{}cOpenTime"/>
 *         &lt;element ref="{}cashierPeriod"/>
 *         &lt;element ref="{}beginCash"/>
 *         &lt;element ref="{}beginFoodStmp" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cashier",
    "posNum",
    "cOpenTime",
    "cashierPeriod",
    "beginCash",
    "beginFoodStmp"
})
@XmlRootElement(name = "openCashier")
public class OpenCashier {

    @XmlElement(required = true)
    protected BaseCashierType cashier;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger posNum;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cOpenTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger cashierPeriod;
    @XmlElement(required = true)
    protected BeginCash beginCash;
    protected BeginFoodStmp beginFoodStmp;

    /**
     * Gets the value of the cashier property.
     * 
     * @return
     *     possible object is
     *     {@link BaseCashierType }
     *     
     */
    public BaseCashierType getCashier() {
        return cashier;
    }

    /**
     * Sets the value of the cashier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseCashierType }
     *     
     */
    public void setCashier(BaseCashierType value) {
        this.cashier = value;
    }

    /**
     * Gets the value of the posNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPosNum() {
        return posNum;
    }

    /**
     * Sets the value of the posNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPosNum(BigInteger value) {
        this.posNum = value;
    }

    /**
     * Gets the value of the cOpenTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCOpenTime() {
        return cOpenTime;
    }

    /**
     * Sets the value of the cOpenTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCOpenTime(XMLGregorianCalendar value) {
        this.cOpenTime = value;
    }

    /**
     * Gets the value of the cashierPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCashierPeriod() {
        return cashierPeriod;
    }

    /**
     * Sets the value of the cashierPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCashierPeriod(BigInteger value) {
        this.cashierPeriod = value;
    }

    /**
     * Gets the value of the beginCash property.
     * 
     * @return
     *     possible object is
     *     {@link BeginCash }
     *     
     */
    public BeginCash getBeginCash() {
        return beginCash;
    }

    /**
     * Sets the value of the beginCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeginCash }
     *     
     */
    public void setBeginCash(BeginCash value) {
        this.beginCash = value;
    }

    /**
     * Gets the value of the beginFoodStmp property.
     * 
     * @return
     *     possible object is
     *     {@link BeginFoodStmp }
     *     
     */
    public BeginFoodStmp getBeginFoodStmp() {
        return beginFoodStmp;
    }

    /**
     * Sets the value of the beginFoodStmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeginFoodStmp }
     *     
     */
    public void setBeginFoodStmp(BeginFoodStmp value) {
        this.beginFoodStmp = value;
    }

}
