//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for priceChangeInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="priceChangeInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}fuelProd"/>
 *         &lt;element ref="{}fuelSvcMode"/>
 *         &lt;element ref="{}fuelMOP"/>
 *         &lt;element ref="{}fuelTier"/>
 *         &lt;element name="previousPrice">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
 *                 &lt;attribute name="sysid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="currentPrice">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
 *                 &lt;attribute name="sysid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="sysid" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "priceChangeInfoType", propOrder = {
    "fuelProd",
    "fuelSvcMode",
    "fuelMOP",
    "fuelTier",
    "previousPrice",
    "currentPrice"
})
public class PriceChangeInfoType {

    @XmlElement(required = true)
    protected FuelProd fuelProd;
    @XmlElement(required = true)
    protected FuelSvcMode fuelSvcMode;
    @XmlElement(required = true)
    protected FuelMOP fuelMOP;
    @XmlElement(required = true)
    protected FuelTier fuelTier;
    @XmlElement(required = true)
    protected PriceChangeInfoType.PreviousPrice previousPrice;
    @XmlElement(required = true)
    protected PriceChangeInfoType.CurrentPrice currentPrice;
    @XmlAttribute(name = "sysid")
    protected BigInteger sysid;

    /**
     * Gets the value of the fuelProd property.
     * 
     * @return
     *     possible object is
     *     {@link FuelProd }
     *     
     */
    public FuelProd getFuelProd() {
        return fuelProd;
    }

    /**
     * Sets the value of the fuelProd property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuelProd }
     *     
     */
    public void setFuelProd(FuelProd value) {
        this.fuelProd = value;
    }

    /**
     * Gets the value of the fuelSvcMode property.
     * 
     * @return
     *     possible object is
     *     {@link FuelSvcMode }
     *     
     */
    public FuelSvcMode getFuelSvcMode() {
        return fuelSvcMode;
    }

    /**
     * Sets the value of the fuelSvcMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuelSvcMode }
     *     
     */
    public void setFuelSvcMode(FuelSvcMode value) {
        this.fuelSvcMode = value;
    }

    /**
     * Gets the value of the fuelMOP property.
     * 
     * @return
     *     possible object is
     *     {@link FuelMOP }
     *     
     */
    public FuelMOP getFuelMOP() {
        return fuelMOP;
    }

    /**
     * Sets the value of the fuelMOP property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuelMOP }
     *     
     */
    public void setFuelMOP(FuelMOP value) {
        this.fuelMOP = value;
    }

    /**
     * Gets the value of the fuelTier property.
     * 
     * @return
     *     possible object is
     *     {@link FuelTier }
     *     
     */
    public FuelTier getFuelTier() {
        return fuelTier;
    }

    /**
     * Sets the value of the fuelTier property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuelTier }
     *     
     */
    public void setFuelTier(FuelTier value) {
        this.fuelTier = value;
    }

    /**
     * Gets the value of the previousPrice property.
     * 
     * @return
     *     possible object is
     *     {@link PriceChangeInfoType.PreviousPrice }
     *     
     */
    public PriceChangeInfoType.PreviousPrice getPreviousPrice() {
        return previousPrice;
    }

    /**
     * Sets the value of the previousPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceChangeInfoType.PreviousPrice }
     *     
     */
    public void setPreviousPrice(PriceChangeInfoType.PreviousPrice value) {
        this.previousPrice = value;
    }

    /**
     * Gets the value of the currentPrice property.
     * 
     * @return
     *     possible object is
     *     {@link PriceChangeInfoType.CurrentPrice }
     *     
     */
    public PriceChangeInfoType.CurrentPrice getCurrentPrice() {
        return currentPrice;
    }

    /**
     * Sets the value of the currentPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceChangeInfoType.CurrentPrice }
     *     
     */
    public void setCurrentPrice(PriceChangeInfoType.CurrentPrice value) {
        this.currentPrice = value;
    }

    /**
     * Gets the value of the sysid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSysid() {
        return sysid;
    }

    /**
     * Sets the value of the sysid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSysid(BigInteger value) {
        this.sysid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
     *       &lt;attribute name="sysid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CurrentPrice {

        @XmlValue
        protected BigDecimal value;
        @XmlAttribute(name = "sysid", required = true)
        protected BigInteger sysid;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the sysid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSysid() {
            return sysid;
        }

        /**
         * Sets the value of the sysid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSysid(BigInteger value) {
            this.sysid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
     *       &lt;attribute name="sysid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PreviousPrice {

        @XmlValue
        protected BigDecimal value;
        @XmlAttribute(name = "sysid", required = true)
        protected BigInteger sysid;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the sysid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSysid() {
            return sysid;
        }

        /**
         * Sets the value of the sysid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSysid(BigInteger value) {
            this.sysid = value;
        }

    }

}
