//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recallTransactionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="recallTransactionType">
 *   &lt;restriction base="{}transactionType">
 *     &lt;enumeration value="sale"/>
 *     &lt;enumeration value="refund sale"/>
 *     &lt;enumeration value="kioskOrder"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "recallTransactionType")
@XmlEnum(TransactionType.class)
public enum RecallTransactionType {

    @XmlEnumValue("sale")
    SALE(TransactionType.SALE),
    @XmlEnumValue("refund sale")
    REFUND_SALE(TransactionType.REFUND_SALE),
    @XmlEnumValue("kioskOrder")
    KIOSK_ORDER(TransactionType.KIOSK_ORDER);
    private final TransactionType value;

    RecallTransactionType(TransactionType v) {
        value = v;
    }

    public TransactionType value() {
        return value;
    }

    public static RecallTransactionType fromValue(TransactionType v) {
        for (RecallTransactionType c: RecallTransactionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
