//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}trHeader"/>
 *         &lt;element ref="{}trJournal" minOccurs="0"/>
 *         &lt;element ref="{}trClock" minOccurs="0"/>
 *         &lt;element ref="{}trValue" minOccurs="0"/>
 *         &lt;element ref="{}trCwsh" minOccurs="0"/>
 *         &lt;element ref="{}trFiscalReceiptInfo" minOccurs="0"/>
 *         &lt;element ref="{}trFiscalTaxExemptInfo" minOccurs="0"/>
 *         &lt;element ref="{}trMixMatches" minOccurs="0"/>
 *         &lt;element ref="{}trLoyalty" minOccurs="0"/>
 *         &lt;element ref="{}trExNetProds" minOccurs="0"/>
 *         &lt;element ref="{}trLines" minOccurs="0"/>
 *         &lt;element ref="{}trPaylines" minOccurs="0"/>
 *         &lt;element ref="{}cashier" minOccurs="0"/>
 *         &lt;element ref="{}posNum" minOccurs="0"/>
 *         &lt;element ref="{}cOpenTime" minOccurs="0"/>
 *         &lt;element ref="{}cCloseTime" minOccurs="0"/>
 *         &lt;element ref="{}beginTicket" minOccurs="0"/>
 *         &lt;element ref="{}endTicket" minOccurs="0"/>
 *         &lt;element ref="{}cashierPeriod" minOccurs="0"/>
 *         &lt;element name="cReportTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element ref="{}ticketCount" minOccurs="0"/>
 *         &lt;element ref="{}beginCash" minOccurs="0"/>
 *         &lt;element ref="{}beginFoodStmp" minOccurs="0"/>
 *         &lt;element ref="{}drawerAmounts" minOccurs="0"/>
 *         &lt;element name="appSpcfcData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}trPriceChange" minOccurs="0"/>
 *         &lt;element name="trScannedCoupons" type="{}trScannedCouponType" minOccurs="0"/>
 *         &lt;element ref="{}reconciledByID" minOccurs="0"/>
 *         &lt;element ref="{}reconciledByName" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{}transactionType" />
 *       &lt;attribute name="rollback" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="underrunCustomer" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="fuelPrepayCompletion" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="fuelPrepay" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="suspended" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="recalled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="choice">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="in"/>
 *             &lt;enumeration value="out"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="backgroundCompletion" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="voidReason" type="{}voidReasonType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trHeader",
    "trJournal",
    "trClock",
    "trValue",
    "trCwsh",
    "trFiscalReceiptInfo",
    "trFiscalTaxExemptInfo",
    "trMixMatches",
    "trLoyalty",
    "trExNetProds",
    "trLines",
    "trPaylines",
    "cashier",
    "posNum",
    "cOpenTime",
    "cCloseTime",
    "beginTicket",
    "endTicket",
    "cashierPeriod",
    "cReportTime",
    "ticketCount",
    "beginCash",
    "beginFoodStmp",
    "drawerAmounts",
    "appSpcfcData",
    "trPriceChange",
    "trScannedCoupons",
    "reconciledByID",
    "reconciledByName"
})
@XmlRootElement(name = "trans")
public class Trans {

    @XmlElement(required = true)
    protected TrHeaderType trHeader;
    protected TrJournal trJournal;
    protected TrClock trClock;
    protected TrValue trValue;
    protected TrCwsh trCwsh;
    protected TrFiscalReceiptInfo trFiscalReceiptInfo;
    protected FiscalTaxExemptType trFiscalTaxExemptInfo;
    protected TrMixMatches trMixMatches;
    protected TrLoyalty trLoyalty;
    protected TrExNetProds trExNetProds;
    protected TrLines trLines;
    protected TrPaylines trPaylines;
    protected BaseCashierType cashier;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger posNum;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cOpenTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cCloseTime;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger beginTicket;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger endTicket;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger cashierPeriod;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cReportTime;
    protected Object ticketCount;
    protected BeginCash beginCash;
    protected BeginFoodStmp beginFoodStmp;
    protected DrawerAmounts drawerAmounts;
    protected Trans.AppSpcfcData appSpcfcData;
    protected TrPriceChange trPriceChange;
    protected TrScannedCouponType trScannedCoupons;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger reconciledByID;
    protected String reconciledByName;
    @XmlAttribute(name = "type", required = true)
    protected TransactionType type;
    @XmlAttribute(name = "rollback")
    protected Boolean rollback;
    @XmlAttribute(name = "underrunCustomer")
    protected Boolean underrunCustomer;
    @XmlAttribute(name = "fuelPrepayCompletion")
    protected Boolean fuelPrepayCompletion;
    @XmlAttribute(name = "fuelPrepay")
    protected Boolean fuelPrepay;
    @XmlAttribute(name = "suspended")
    protected Boolean suspended;
    @XmlAttribute(name = "recalled")
    protected Boolean recalled;
    @XmlAttribute(name = "choice")
    protected String choice;
    @XmlAttribute(name = "backgroundCompletion")
    protected Boolean backgroundCompletion;
    @XmlAttribute(name = "voidReason")
    protected VoidReasonType voidReason;

    /**
     * Gets the value of the trHeader property.
     * 
     * @return
     *     possible object is
     *     {@link TrHeaderType }
     *     
     */
    public TrHeaderType getTrHeader() {
        return trHeader;
    }

    /**
     * Sets the value of the trHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrHeaderType }
     *     
     */
    public void setTrHeader(TrHeaderType value) {
        this.trHeader = value;
    }

    /**
     * Gets the value of the trJournal property.
     * 
     * @return
     *     possible object is
     *     {@link TrJournal }
     *     
     */
    public TrJournal getTrJournal() {
        return trJournal;
    }

    /**
     * Sets the value of the trJournal property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrJournal }
     *     
     */
    public void setTrJournal(TrJournal value) {
        this.trJournal = value;
    }

    /**
     * Gets the value of the trClock property.
     * 
     * @return
     *     possible object is
     *     {@link TrClock }
     *     
     */
    public TrClock getTrClock() {
        return trClock;
    }

    /**
     * Sets the value of the trClock property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrClock }
     *     
     */
    public void setTrClock(TrClock value) {
        this.trClock = value;
    }

    /**
     * Gets the value of the trValue property.
     * 
     * @return
     *     possible object is
     *     {@link TrValue }
     *     
     */
    public TrValue getTrValue() {
        return trValue;
    }

    /**
     * Sets the value of the trValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrValue }
     *     
     */
    public void setTrValue(TrValue value) {
        this.trValue = value;
    }

    /**
     * Gets the value of the trCwsh property.
     * 
     * @return
     *     possible object is
     *     {@link TrCwsh }
     *     
     */
    public TrCwsh getTrCwsh() {
        return trCwsh;
    }

    /**
     * Sets the value of the trCwsh property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrCwsh }
     *     
     */
    public void setTrCwsh(TrCwsh value) {
        this.trCwsh = value;
    }

    /**
     * Gets the value of the trFiscalReceiptInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TrFiscalReceiptInfo }
     *     
     */
    public TrFiscalReceiptInfo getTrFiscalReceiptInfo() {
        return trFiscalReceiptInfo;
    }

    /**
     * Sets the value of the trFiscalReceiptInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrFiscalReceiptInfo }
     *     
     */
    public void setTrFiscalReceiptInfo(TrFiscalReceiptInfo value) {
        this.trFiscalReceiptInfo = value;
    }

    /**
     * Fiscal Tax Exempt Information for Global Commander
     * 
     * @return
     *     possible object is
     *     {@link FiscalTaxExemptType }
     *     
     */
    public FiscalTaxExemptType getTrFiscalTaxExemptInfo() {
        return trFiscalTaxExemptInfo;
    }

    /**
     * Sets the value of the trFiscalTaxExemptInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiscalTaxExemptType }
     *     
     */
    public void setTrFiscalTaxExemptInfo(FiscalTaxExemptType value) {
        this.trFiscalTaxExemptInfo = value;
    }

    /**
     * Gets the value of the trMixMatches property.
     * 
     * @return
     *     possible object is
     *     {@link TrMixMatches }
     *     
     */
    public TrMixMatches getTrMixMatches() {
        return trMixMatches;
    }

    /**
     * Sets the value of the trMixMatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrMixMatches }
     *     
     */
    public void setTrMixMatches(TrMixMatches value) {
        this.trMixMatches = value;
    }

    /**
     * Gets the value of the trLoyalty property.
     * 
     * @return
     *     possible object is
     *     {@link TrLoyalty }
     *     
     */
    public TrLoyalty getTrLoyalty() {
        return trLoyalty;
    }

    /**
     * Sets the value of the trLoyalty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrLoyalty }
     *     
     */
    public void setTrLoyalty(TrLoyalty value) {
        this.trLoyalty = value;
    }

    /**
     * Gets the value of the trExNetProds property.
     * 
     * @return
     *     possible object is
     *     {@link TrExNetProds }
     *     
     */
    public TrExNetProds getTrExNetProds() {
        return trExNetProds;
    }

    /**
     * Sets the value of the trExNetProds property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrExNetProds }
     *     
     */
    public void setTrExNetProds(TrExNetProds value) {
        this.trExNetProds = value;
    }

    /**
     * Gets the value of the trLines property.
     * 
     * @return
     *     possible object is
     *     {@link TrLines }
     *     
     */
    public TrLines getTrLines() {
        return trLines;
    }

    /**
     * Sets the value of the trLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrLines }
     *     
     */
    public void setTrLines(TrLines value) {
        this.trLines = value;
    }

    /**
     * Gets the value of the trPaylines property.
     * 
     * @return
     *     possible object is
     *     {@link TrPaylines }
     *     
     */
    public TrPaylines getTrPaylines() {
        return trPaylines;
    }

    /**
     * Sets the value of the trPaylines property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrPaylines }
     *     
     */
    public void setTrPaylines(TrPaylines value) {
        this.trPaylines = value;
    }

    /**
     * Gets the value of the cashier property.
     * 
     * @return
     *     possible object is
     *     {@link BaseCashierType }
     *     
     */
    public BaseCashierType getCashier() {
        return cashier;
    }

    /**
     * Sets the value of the cashier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseCashierType }
     *     
     */
    public void setCashier(BaseCashierType value) {
        this.cashier = value;
    }

    /**
     * Gets the value of the posNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPosNum() {
        return posNum;
    }

    /**
     * Sets the value of the posNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPosNum(BigInteger value) {
        this.posNum = value;
    }

    /**
     * Gets the value of the cOpenTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCOpenTime() {
        return cOpenTime;
    }

    /**
     * Sets the value of the cOpenTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCOpenTime(XMLGregorianCalendar value) {
        this.cOpenTime = value;
    }

    /**
     * Gets the value of the cCloseTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCCloseTime() {
        return cCloseTime;
    }

    /**
     * Sets the value of the cCloseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCCloseTime(XMLGregorianCalendar value) {
        this.cCloseTime = value;
    }

    /**
     * Gets the value of the beginTicket property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBeginTicket() {
        return beginTicket;
    }

    /**
     * Sets the value of the beginTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBeginTicket(BigInteger value) {
        this.beginTicket = value;
    }

    /**
     * Gets the value of the endTicket property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEndTicket() {
        return endTicket;
    }

    /**
     * Sets the value of the endTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEndTicket(BigInteger value) {
        this.endTicket = value;
    }

    /**
     * Gets the value of the cashierPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCashierPeriod() {
        return cashierPeriod;
    }

    /**
     * Sets the value of the cashierPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCashierPeriod(BigInteger value) {
        this.cashierPeriod = value;
    }

    /**
     * Gets the value of the cReportTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCReportTime() {
        return cReportTime;
    }

    /**
     * Sets the value of the cReportTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCReportTime(XMLGregorianCalendar value) {
        this.cReportTime = value;
    }

    /**
     * Gets the value of the ticketCount property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTicketCount() {
        return ticketCount;
    }

    /**
     * Sets the value of the ticketCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTicketCount(Object value) {
        this.ticketCount = value;
    }

    /**
     * Gets the value of the beginCash property.
     * 
     * @return
     *     possible object is
     *     {@link BeginCash }
     *     
     */
    public BeginCash getBeginCash() {
        return beginCash;
    }

    /**
     * Sets the value of the beginCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeginCash }
     *     
     */
    public void setBeginCash(BeginCash value) {
        this.beginCash = value;
    }

    /**
     * Gets the value of the beginFoodStmp property.
     * 
     * @return
     *     possible object is
     *     {@link BeginFoodStmp }
     *     
     */
    public BeginFoodStmp getBeginFoodStmp() {
        return beginFoodStmp;
    }

    /**
     * Sets the value of the beginFoodStmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeginFoodStmp }
     *     
     */
    public void setBeginFoodStmp(BeginFoodStmp value) {
        this.beginFoodStmp = value;
    }

    /**
     * Gets the value of the drawerAmounts property.
     * 
     * @return
     *     possible object is
     *     {@link DrawerAmounts }
     *     
     */
    public DrawerAmounts getDrawerAmounts() {
        return drawerAmounts;
    }

    /**
     * Sets the value of the drawerAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrawerAmounts }
     *     
     */
    public void setDrawerAmounts(DrawerAmounts value) {
        this.drawerAmounts = value;
    }

    /**
     * Gets the value of the appSpcfcData property.
     * 
     * @return
     *     possible object is
     *     {@link Trans.AppSpcfcData }
     *     
     */
    public Trans.AppSpcfcData getAppSpcfcData() {
        return appSpcfcData;
    }

    /**
     * Sets the value of the appSpcfcData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trans.AppSpcfcData }
     *     
     */
    public void setAppSpcfcData(Trans.AppSpcfcData value) {
        this.appSpcfcData = value;
    }

    /**
     * Gets the value of the trPriceChange property.
     * 
     * @return
     *     possible object is
     *     {@link TrPriceChange }
     *     
     */
    public TrPriceChange getTrPriceChange() {
        return trPriceChange;
    }

    /**
     * Sets the value of the trPriceChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrPriceChange }
     *     
     */
    public void setTrPriceChange(TrPriceChange value) {
        this.trPriceChange = value;
    }

    /**
     * Gets the value of the trScannedCoupons property.
     * 
     * @return
     *     possible object is
     *     {@link TrScannedCouponType }
     *     
     */
    public TrScannedCouponType getTrScannedCoupons() {
        return trScannedCoupons;
    }

    /**
     * Sets the value of the trScannedCoupons property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrScannedCouponType }
     *     
     */
    public void setTrScannedCoupons(TrScannedCouponType value) {
        this.trScannedCoupons = value;
    }

    /**
     * Gets the value of the reconciledByID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReconciledByID() {
        return reconciledByID;
    }

    /**
     * Sets the value of the reconciledByID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReconciledByID(BigInteger value) {
        this.reconciledByID = value;
    }

    /**
     * Gets the value of the reconciledByName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReconciledByName() {
        return reconciledByName;
    }

    /**
     * Sets the value of the reconciledByName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReconciledByName(String value) {
        this.reconciledByName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionType }
     *     
     */
    public TransactionType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionType }
     *     
     */
    public void setType(TransactionType value) {
        this.type = value;
    }

    /**
     * Gets the value of the rollback property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRollback() {
        if (rollback == null) {
            return false;
        } else {
            return rollback;
        }
    }

    /**
     * Sets the value of the rollback property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRollback(Boolean value) {
        this.rollback = value;
    }

    /**
     * Gets the value of the underrunCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUnderrunCustomer() {
        if (underrunCustomer == null) {
            return false;
        } else {
            return underrunCustomer;
        }
    }

    /**
     * Sets the value of the underrunCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnderrunCustomer(Boolean value) {
        this.underrunCustomer = value;
    }

    /**
     * Gets the value of the fuelPrepayCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFuelPrepayCompletion() {
        if (fuelPrepayCompletion == null) {
            return false;
        } else {
            return fuelPrepayCompletion;
        }
    }

    /**
     * Sets the value of the fuelPrepayCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFuelPrepayCompletion(Boolean value) {
        this.fuelPrepayCompletion = value;
    }

    /**
     * Gets the value of the fuelPrepay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFuelPrepay() {
        if (fuelPrepay == null) {
            return false;
        } else {
            return fuelPrepay;
        }
    }

    /**
     * Sets the value of the fuelPrepay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFuelPrepay(Boolean value) {
        this.fuelPrepay = value;
    }

    /**
     * Gets the value of the suspended property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSuspended() {
        if (suspended == null) {
            return false;
        } else {
            return suspended;
        }
    }

    /**
     * Sets the value of the suspended property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSuspended(Boolean value) {
        this.suspended = value;
    }

    /**
     * Gets the value of the recalled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRecalled() {
        if (recalled == null) {
            return false;
        } else {
            return recalled;
        }
    }

    /**
     * Sets the value of the recalled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRecalled(Boolean value) {
        this.recalled = value;
    }

    /**
     * Gets the value of the choice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoice() {
        return choice;
    }

    /**
     * Sets the value of the choice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoice(String value) {
        this.choice = value;
    }

    /**
     * Gets the value of the backgroundCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBackgroundCompletion() {
        if (backgroundCompletion == null) {
            return false;
        } else {
            return backgroundCompletion;
        }
    }

    /**
     * Sets the value of the backgroundCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBackgroundCompletion(Boolean value) {
        this.backgroundCompletion = value;
    }

    /**
     * Gets the value of the voidReason property.
     * 
     * @return
     *     possible object is
     *     {@link VoidReasonType }
     *     
     */
    public VoidReasonType getVoidReason() {
        return voidReason;
    }

    /**
     * Sets the value of the voidReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoidReasonType }
     *     
     */
    public void setVoidReason(VoidReasonType value) {
        this.voidReason = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AppSpcfcData {


    }

}
