//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="authName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="authNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchantTaxId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="receiptName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="receiptNumber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="beginSequence" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="endSequence" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="originalReceiptNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerTaxId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="voucherNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="startAuthDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="endAuthDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="fiscalSale"/>
 *             &lt;enumeration value="fiscalRefund"/>
 *             &lt;enumeration value="fuelVoucher"/>
 *             &lt;enumeration value="nonFiscalNetwork"/>
 *             &lt;enumeration value="pumpTest"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authName",
    "authNumber",
    "merchantTaxId",
    "receiptName",
    "receiptNumber",
    "originalReceiptNumber",
    "customerName",
    "customerTaxId",
    "voucherNumber",
    "customerNumber",
    "startAuthDate",
    "endAuthDate"
})
@XmlRootElement(name = "trFiscalReceiptInfo")
public class TrFiscalReceiptInfo {

    protected String authName;
    protected String authNumber;
    protected String merchantTaxId;
    protected String receiptName;
    protected TrFiscalReceiptInfo.ReceiptNumber receiptNumber;
    protected String originalReceiptNumber;
    protected String customerName;
    protected String customerTaxId;
    protected String voucherNumber;
    protected String customerNumber;
    protected String startAuthDate;
    protected String endAuthDate;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the authName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * Sets the value of the authName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthName(String value) {
        this.authName = value;
    }

    /**
     * Gets the value of the authNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthNumber() {
        return authNumber;
    }

    /**
     * Sets the value of the authNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthNumber(String value) {
        this.authNumber = value;
    }

    /**
     * Gets the value of the merchantTaxId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantTaxId() {
        return merchantTaxId;
    }

    /**
     * Sets the value of the merchantTaxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantTaxId(String value) {
        this.merchantTaxId = value;
    }

    /**
     * Gets the value of the receiptName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptName() {
        return receiptName;
    }

    /**
     * Sets the value of the receiptName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptName(String value) {
        this.receiptName = value;
    }

    /**
     * Gets the value of the receiptNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TrFiscalReceiptInfo.ReceiptNumber }
     *     
     */
    public TrFiscalReceiptInfo.ReceiptNumber getReceiptNumber() {
        return receiptNumber;
    }

    /**
     * Sets the value of the receiptNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrFiscalReceiptInfo.ReceiptNumber }
     *     
     */
    public void setReceiptNumber(TrFiscalReceiptInfo.ReceiptNumber value) {
        this.receiptNumber = value;
    }

    /**
     * Gets the value of the originalReceiptNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalReceiptNumber() {
        return originalReceiptNumber;
    }

    /**
     * Sets the value of the originalReceiptNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalReceiptNumber(String value) {
        this.originalReceiptNumber = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the customerTaxId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerTaxId() {
        return customerTaxId;
    }

    /**
     * Sets the value of the customerTaxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerTaxId(String value) {
        this.customerTaxId = value;
    }

    /**
     * Gets the value of the voucherNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherNumber() {
        return voucherNumber;
    }

    /**
     * Sets the value of the voucherNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherNumber(String value) {
        this.voucherNumber = value;
    }

    /**
     * Gets the value of the customerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * Sets the value of the customerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNumber(String value) {
        this.customerNumber = value;
    }

    /**
     * Gets the value of the startAuthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartAuthDate() {
        return startAuthDate;
    }

    /**
     * Sets the value of the startAuthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartAuthDate(String value) {
        this.startAuthDate = value;
    }

    /**
     * Gets the value of the endAuthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndAuthDate() {
        return endAuthDate;
    }

    /**
     * Sets the value of the endAuthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndAuthDate(String value) {
        this.endAuthDate = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="beginSequence" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="endSequence" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ReceiptNumber {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "beginSequence")
        protected String beginSequence;
        @XmlAttribute(name = "endSequence")
        protected String endSequence;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the beginSequence property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeginSequence() {
            return beginSequence;
        }

        /**
         * Sets the value of the beginSequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeginSequence(String value) {
            this.beginSequence = value;
        }

        /**
         * Gets the value of the endSequence property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEndSequence() {
            return endSequence;
        }

        /**
         * Sets the value of the endSequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEndSequence(String value) {
            this.endSequence = value;
        }

    }

}
