//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for trHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}termMsgSN" minOccurs="0"/>
 *         &lt;element ref="{}trTickNum" minOccurs="0"/>
 *         &lt;element ref="{}trOriginalTickNum" minOccurs="0"/>
 *         &lt;element name="trUniqueSN" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element ref="{}trRecall" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="trKioskOrder" type="{}trTickNum" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}period" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}date" minOccurs="0"/>
 *         &lt;element ref="{}duration" minOccurs="0"/>
 *         &lt;element ref="{}till" minOccurs="0"/>
 *         &lt;element ref="{}cashier" minOccurs="0"/>
 *         &lt;element ref="{}originalCashier" minOccurs="0"/>
 *         &lt;element ref="{}posNum" minOccurs="0"/>
 *         &lt;element ref="{}storeNumber" minOccurs="0"/>
 *         &lt;element ref="{}trMiscRefNum" minOccurs="0"/>
 *         &lt;element ref="{}trFuelOnlyCst" minOccurs="0"/>
 *         &lt;element ref="{}trFuelDeposit" minOccurs="0"/>
 *         &lt;element ref="{}trHouseAcct" minOccurs="0"/>
 *         &lt;element ref="{}trVendorPmt" minOccurs="0"/>
 *         &lt;element ref="{}trPrePayComp" minOccurs="0"/>
 *         &lt;element ref="{}popCodeUsed" minOccurs="0"/>
 *         &lt;element name="popDiscTran" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="popDiscMem" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="popCouponGen" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="popCodeGen" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="popCodes" type="{}popCodesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}coinDispensed" minOccurs="0"/>
 *         &lt;element name="clockCashier" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="clockDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="jobCode" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="periodName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="periodType" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="periodSeq" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element ref="{}originalSafeDropInfo" minOccurs="0"/>
 *         &lt;element name="eSafeId" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="sysid" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="priceChangedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="priceChangeOrigin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}mwsEnabled" minOccurs="0"/>
 *         &lt;element name="locationId" type="{}locationIdType" minOccurs="0"/>
 *         &lt;element name="user" type="{}userType" minOccurs="0"/>
 *         &lt;element name="trOvrdCshr" type="{}ovrdCshrType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="physicalRegisterID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trHeaderType", propOrder = {
    "termMsgSN",
    "trTickNum",
    "trOriginalTickNum",
    "trUniqueSN",
    "trRecall",
    "trKioskOrder",
    "period",
    "date",
    "duration",
    "till",
    "cashier",
    "originalCashier",
    "posNum",
    "storeNumber",
    "trMiscRefNum",
    "trFuelOnlyCst",
    "trFuelDeposit",
    "trHouseAcct",
    "trVendorPmt",
    "trPrePayComp",
    "popCodeUsed",
    "popDiscTran",
    "popDiscMem",
    "popCouponGen",
    "popCodeGen",
    "popCodes",
    "coinDispensed",
    "clockCashier",
    "clockDate",
    "jobCode",
    "periodName",
    "periodType",
    "periodSeq",
    "originalSafeDropInfo",
    "eSafeId",
    "priceChangedBy",
    "priceChangeOrigin",
    "mwsEnabled",
    "locationId",
    "user",
    "trOvrdCshr",
    "physicalRegisterID"
})
public class TrHeaderType {

    protected TermMsgSN termMsgSN;
    protected TrTickNum trTickNum;
    protected TrTickNum trOriginalTickNum;
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger trUniqueSN;
    protected List<TrRecall> trRecall;
    protected List<TrTickNum> trKioskOrder;
    protected List<Period> period;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;
    protected BigInteger duration;
    protected Integer till;
    protected BaseCashierType cashier;
    protected BaseCashierType originalCashier;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger posNum;
    protected String storeNumber;
    protected String trMiscRefNum;
    protected String trFuelOnlyCst;
    protected String trFuelDeposit;
    protected TrHouseAcct trHouseAcct;
    protected String trVendorPmt;
    protected String trPrePayComp;
    protected String popCodeUsed;
    protected Object popDiscTran;
    protected Object popDiscMem;
    protected Object popCouponGen;
    protected Object popCodeGen;
    protected List<PopCodesType> popCodes;
    protected BigDecimal coinDispensed;
    protected BigInteger clockCashier;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar clockDate;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger jobCode;
    protected String periodName;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger periodType;
    @XmlSchemaType(name = "unsignedInt")
    protected Long periodSeq;
    protected OriginalSafeDropInfo originalSafeDropInfo;
    protected TrHeaderType.ESafeId eSafeId;
    protected String priceChangedBy;
    protected String priceChangeOrigin;
    protected BigInteger mwsEnabled;
    protected String locationId;
    protected UserType user;
    protected List<OvrdCshrType> trOvrdCshr;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger physicalRegisterID;

    /**
     * Gets the value of the termMsgSN property.
     * 
     * @return
     *     possible object is
     *     {@link TermMsgSN }
     *     
     */
    public TermMsgSN getTermMsgSN() {
        return termMsgSN;
    }

    /**
     * Sets the value of the termMsgSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermMsgSN }
     *     
     */
    public void setTermMsgSN(TermMsgSN value) {
        this.termMsgSN = value;
    }

    /**
     * Gets the value of the trTickNum property.
     * 
     * @return
     *     possible object is
     *     {@link TrTickNum }
     *     
     */
    public TrTickNum getTrTickNum() {
        return trTickNum;
    }

    /**
     * Sets the value of the trTickNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrTickNum }
     *     
     */
    public void setTrTickNum(TrTickNum value) {
        this.trTickNum = value;
    }

    /**
     * Gets the value of the trOriginalTickNum property.
     * 
     * @return
     *     possible object is
     *     {@link TrTickNum }
     *     
     */
    public TrTickNum getTrOriginalTickNum() {
        return trOriginalTickNum;
    }

    /**
     * Sets the value of the trOriginalTickNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrTickNum }
     *     
     */
    public void setTrOriginalTickNum(TrTickNum value) {
        this.trOriginalTickNum = value;
    }

    /**
     * Gets the value of the trUniqueSN property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrUniqueSN() {
        return trUniqueSN;
    }

    /**
     * Sets the value of the trUniqueSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrUniqueSN(BigInteger value) {
        this.trUniqueSN = value;
    }

    /**
     * Gets the value of the trRecall property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trRecall property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrRecall().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrRecall }
     * 
     * 
     */
    public List<TrRecall> getTrRecall() {
        if (trRecall == null) {
            trRecall = new ArrayList<TrRecall>();
        }
        return this.trRecall;
    }

    /**
     * Gets the value of the trKioskOrder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trKioskOrder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrKioskOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrTickNum }
     * 
     * 
     */
    public List<TrTickNum> getTrKioskOrder() {
        if (trKioskOrder == null) {
            trKioskOrder = new ArrayList<TrTickNum>();
        }
        return this.trKioskOrder;
    }

    /**
     * Gets the value of the period property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the period property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Period }
     * 
     * 
     */
    public List<Period> getPeriod() {
        if (period == null) {
            period = new ArrayList<Period>();
        }
        return this.period;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDuration(BigInteger value) {
        this.duration = value;
    }

    /**
     * Gets the value of the till property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTill() {
        return till;
    }

    /**
     * Sets the value of the till property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTill(Integer value) {
        this.till = value;
    }

    /**
     * Gets the value of the cashier property.
     * 
     * @return
     *     possible object is
     *     {@link BaseCashierType }
     *     
     */
    public BaseCashierType getCashier() {
        return cashier;
    }

    /**
     * Sets the value of the cashier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseCashierType }
     *     
     */
    public void setCashier(BaseCashierType value) {
        this.cashier = value;
    }

    /**
     * Gets the value of the originalCashier property.
     * 
     * @return
     *     possible object is
     *     {@link BaseCashierType }
     *     
     */
    public BaseCashierType getOriginalCashier() {
        return originalCashier;
    }

    /**
     * Sets the value of the originalCashier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseCashierType }
     *     
     */
    public void setOriginalCashier(BaseCashierType value) {
        this.originalCashier = value;
    }

    /**
     * Gets the value of the posNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPosNum() {
        return posNum;
    }

    /**
     * Sets the value of the posNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPosNum(BigInteger value) {
        this.posNum = value;
    }

    /**
     * Gets the value of the storeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreNumber() {
        return storeNumber;
    }

    /**
     * Sets the value of the storeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreNumber(String value) {
        this.storeNumber = value;
    }

    /**
     * Gets the value of the trMiscRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrMiscRefNum() {
        return trMiscRefNum;
    }

    /**
     * Sets the value of the trMiscRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrMiscRefNum(String value) {
        this.trMiscRefNum = value;
    }

    /**
     * Gets the value of the trFuelOnlyCst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrFuelOnlyCst() {
        return trFuelOnlyCst;
    }

    /**
     * Sets the value of the trFuelOnlyCst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrFuelOnlyCst(String value) {
        this.trFuelOnlyCst = value;
    }

    /**
     * Gets the value of the trFuelDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrFuelDeposit() {
        return trFuelDeposit;
    }

    /**
     * Sets the value of the trFuelDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrFuelDeposit(String value) {
        this.trFuelDeposit = value;
    }

    /**
     * Gets the value of the trHouseAcct property.
     * 
     * @return
     *     possible object is
     *     {@link TrHouseAcct }
     *     
     */
    public TrHouseAcct getTrHouseAcct() {
        return trHouseAcct;
    }

    /**
     * Sets the value of the trHouseAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrHouseAcct }
     *     
     */
    public void setTrHouseAcct(TrHouseAcct value) {
        this.trHouseAcct = value;
    }

    /**
     * Gets the value of the trVendorPmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrVendorPmt() {
        return trVendorPmt;
    }

    /**
     * Sets the value of the trVendorPmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrVendorPmt(String value) {
        this.trVendorPmt = value;
    }

    /**
     * Gets the value of the trPrePayComp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrPrePayComp() {
        return trPrePayComp;
    }

    /**
     * Sets the value of the trPrePayComp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrPrePayComp(String value) {
        this.trPrePayComp = value;
    }

    /**
     * Gets the value of the popCodeUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopCodeUsed() {
        return popCodeUsed;
    }

    /**
     * Sets the value of the popCodeUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopCodeUsed(String value) {
        this.popCodeUsed = value;
    }

    /**
     * Gets the value of the popDiscTran property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPopDiscTran() {
        return popDiscTran;
    }

    /**
     * Sets the value of the popDiscTran property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPopDiscTran(Object value) {
        this.popDiscTran = value;
    }

    /**
     * Gets the value of the popDiscMem property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPopDiscMem() {
        return popDiscMem;
    }

    /**
     * Sets the value of the popDiscMem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPopDiscMem(Object value) {
        this.popDiscMem = value;
    }

    /**
     * Gets the value of the popCouponGen property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPopCouponGen() {
        return popCouponGen;
    }

    /**
     * Sets the value of the popCouponGen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPopCouponGen(Object value) {
        this.popCouponGen = value;
    }

    /**
     * Gets the value of the popCodeGen property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPopCodeGen() {
        return popCodeGen;
    }

    /**
     * Sets the value of the popCodeGen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPopCodeGen(Object value) {
        this.popCodeGen = value;
    }

    /**
     * Gets the value of the popCodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the popCodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPopCodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PopCodesType }
     * 
     * 
     */
    public List<PopCodesType> getPopCodes() {
        if (popCodes == null) {
            popCodes = new ArrayList<PopCodesType>();
        }
        return this.popCodes;
    }

    /**
     * Gets the value of the coinDispensed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoinDispensed() {
        return coinDispensed;
    }

    /**
     * Sets the value of the coinDispensed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoinDispensed(BigDecimal value) {
        this.coinDispensed = value;
    }

    /**
     * Gets the value of the clockCashier property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClockCashier() {
        return clockCashier;
    }

    /**
     * Sets the value of the clockCashier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClockCashier(BigInteger value) {
        this.clockCashier = value;
    }

    /**
     * Gets the value of the clockDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getClockDate() {
        return clockDate;
    }

    /**
     * Sets the value of the clockDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setClockDate(XMLGregorianCalendar value) {
        this.clockDate = value;
    }

    /**
     * Gets the value of the jobCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getJobCode() {
        return jobCode;
    }

    /**
     * Sets the value of the jobCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setJobCode(BigInteger value) {
        this.jobCode = value;
    }

    /**
     * Gets the value of the periodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodName() {
        return periodName;
    }

    /**
     * Sets the value of the periodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodName(String value) {
        this.periodName = value;
    }

    /**
     * Gets the value of the periodType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPeriodType() {
        return periodType;
    }

    /**
     * Sets the value of the periodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPeriodType(BigInteger value) {
        this.periodType = value;
    }

    /**
     * Gets the value of the periodSeq property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPeriodSeq() {
        return periodSeq;
    }

    /**
     * Sets the value of the periodSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPeriodSeq(Long value) {
        this.periodSeq = value;
    }

    /**
     * Gets the value of the originalSafeDropInfo property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalSafeDropInfo }
     *     
     */
    public OriginalSafeDropInfo getOriginalSafeDropInfo() {
        return originalSafeDropInfo;
    }

    /**
     * Sets the value of the originalSafeDropInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalSafeDropInfo }
     *     
     */
    public void setOriginalSafeDropInfo(OriginalSafeDropInfo value) {
        this.originalSafeDropInfo = value;
    }

    /**
     * Gets the value of the eSafeId property.
     * 
     * @return
     *     possible object is
     *     {@link TrHeaderType.ESafeId }
     *     
     */
    public TrHeaderType.ESafeId getESafeId() {
        return eSafeId;
    }

    /**
     * Sets the value of the eSafeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrHeaderType.ESafeId }
     *     
     */
    public void setESafeId(TrHeaderType.ESafeId value) {
        this.eSafeId = value;
    }

    /**
     * Gets the value of the priceChangedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceChangedBy() {
        return priceChangedBy;
    }

    /**
     * Sets the value of the priceChangedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceChangedBy(String value) {
        this.priceChangedBy = value;
    }

    /**
     * Gets the value of the priceChangeOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceChangeOrigin() {
        return priceChangeOrigin;
    }

    /**
     * Sets the value of the priceChangeOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceChangeOrigin(String value) {
        this.priceChangeOrigin = value;
    }

    /**
     * Gets the value of the mwsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMwsEnabled() {
        return mwsEnabled;
    }

    /**
     * Sets the value of the mwsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMwsEnabled(BigInteger value) {
        this.mwsEnabled = value;
    }

    /**
     * Gets the value of the locationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * Sets the value of the locationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationId(String value) {
        this.locationId = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setUser(UserType value) {
        this.user = value;
    }

    /**
     * Gets the value of the trOvrdCshr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trOvrdCshr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrOvrdCshr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OvrdCshrType }
     * 
     * 
     */
    public List<OvrdCshrType> getTrOvrdCshr() {
        if (trOvrdCshr == null) {
            trOvrdCshr = new ArrayList<OvrdCshrType>();
        }
        return this.trOvrdCshr;
    }

    /**
     * Gets the value of the physicalRegisterID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPhysicalRegisterID() {
        return physicalRegisterID;
    }

    /**
     * Sets the value of the physicalRegisterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPhysicalRegisterID(BigInteger value) {
        this.physicalRegisterID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="sysid" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ESafeId {

        @XmlAttribute(name = "sysid", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger sysid;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the sysid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSysid() {
            return sysid;
        }

        /**
         * Sets the value of the sysid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSysid(BigInteger value) {
            this.sysid = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
