//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for trjTextTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="trjTextTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALERT"/>
 *     &lt;enumeration value="AUTO UPGRADE"/>
 *     &lt;enumeration value="CHANGE QTY"/>
 *     &lt;enumeration value="CWPP CASH RECON EVENT"/>
 *     &lt;enumeration value="CWPP CLOSE"/>
 *     &lt;enumeration value="CWPP INIT"/>
 *     &lt;enumeration value="CWPP REJECT"/>
 *     &lt;enumeration value="DRAWER VIOLATION EVENT"/>
 *     &lt;enumeration value="EPS MESSAGE"/>
 *     &lt;enumeration value="ERROR CORRECT"/>
 *     &lt;enumeration value="FUEL EVENT"/>
 *     &lt;enumeration value="DCR EVENT"/>
 *     &lt;enumeration value="LOGIN/LOGOUT"/>
 *     &lt;enumeration value="OTHER"/>
 *     &lt;enumeration value="PAY OUT EVENT"/>
 *     &lt;enumeration value="POP MESSAGE"/>
 *     &lt;enumeration value="PREPAID TOR DECLINE"/>
 *     &lt;enumeration value="SAFE DROP EVENT"/>
 *     &lt;enumeration value="SALES EVENT"/>
 *     &lt;enumeration value="SECURE USER"/>
 *     &lt;enumeration value="CAR WASH DEVICE STATUS EVENT"/>
 *     &lt;enumeration value="CAR WASH FEATURE STATUS EVENT"/>
 *     &lt;enumeration value="TLS DEVICE STATUS EVENT"/>
 *     &lt;enumeration value="SAFE LOAN EVENT"/>
 *     &lt;enumeration value="PRICE CHECK"/>
 *     &lt;enumeration value="EPS PREPAID PURCHASE PMT ENTRY"/>
 *     &lt;enumeration value="APPLY UPDATES"/>
 *     &lt;enumeration value="EXCEPTION COMMITTING TRANSACTION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "trjTextTypes")
@XmlEnum
public enum TrjTextTypes {

    ALERT("ALERT"),
    @XmlEnumValue("AUTO UPGRADE")
    AUTO_UPGRADE("AUTO UPGRADE"),
    @XmlEnumValue("CHANGE QTY")
    CHANGE_QTY("CHANGE QTY"),
    @XmlEnumValue("CWPP CASH RECON EVENT")
    CWPP_CASH_RECON_EVENT("CWPP CASH RECON EVENT"),
    @XmlEnumValue("CWPP CLOSE")
    CWPP_CLOSE("CWPP CLOSE"),
    @XmlEnumValue("CWPP INIT")
    CWPP_INIT("CWPP INIT"),
    @XmlEnumValue("CWPP REJECT")
    CWPP_REJECT("CWPP REJECT"),
    @XmlEnumValue("DRAWER VIOLATION EVENT")
    DRAWER_VIOLATION_EVENT("DRAWER VIOLATION EVENT"),
    @XmlEnumValue("EPS MESSAGE")
    EPS_MESSAGE("EPS MESSAGE"),
    @XmlEnumValue("ERROR CORRECT")
    ERROR_CORRECT("ERROR CORRECT"),
    @XmlEnumValue("FUEL EVENT")
    FUEL_EVENT("FUEL EVENT"),
    @XmlEnumValue("DCR EVENT")
    DCR_EVENT("DCR EVENT"),
    @XmlEnumValue("LOGIN/LOGOUT")
    LOGIN_LOGOUT("LOGIN/LOGOUT"),
    OTHER("OTHER"),
    @XmlEnumValue("PAY OUT EVENT")
    PAY_OUT_EVENT("PAY OUT EVENT"),
    @XmlEnumValue("POP MESSAGE")
    POP_MESSAGE("POP MESSAGE"),
    @XmlEnumValue("PREPAID TOR DECLINE")
    PREPAID_TOR_DECLINE("PREPAID TOR DECLINE"),
    @XmlEnumValue("SAFE DROP EVENT")
    SAFE_DROP_EVENT("SAFE DROP EVENT"),
    @XmlEnumValue("SALES EVENT")
    SALES_EVENT("SALES EVENT"),
    @XmlEnumValue("SECURE USER")
    SECURE_USER("SECURE USER"),
    @XmlEnumValue("CAR WASH DEVICE STATUS EVENT")
    CAR_WASH_DEVICE_STATUS_EVENT("CAR WASH DEVICE STATUS EVENT"),
    @XmlEnumValue("CAR WASH FEATURE STATUS EVENT")
    CAR_WASH_FEATURE_STATUS_EVENT("CAR WASH FEATURE STATUS EVENT"),
    @XmlEnumValue("TLS DEVICE STATUS EVENT")
    TLS_DEVICE_STATUS_EVENT("TLS DEVICE STATUS EVENT"),
    @XmlEnumValue("SAFE LOAN EVENT")
    SAFE_LOAN_EVENT("SAFE LOAN EVENT"),
    @XmlEnumValue("PRICE CHECK")
    PRICE_CHECK("PRICE CHECK"),
    @XmlEnumValue("EPS PREPAID PURCHASE PMT ENTRY")
    EPS_PREPAID_PURCHASE_PMT_ENTRY("EPS PREPAID PURCHASE PMT ENTRY"),
    @XmlEnumValue("APPLY UPDATES")
    APPLY_UPDATES("APPLY UPDATES"),
    @XmlEnumValue("EXCEPTION COMMITTING TRANSACTION")
    EXCEPTION_COMMITTING_TRANSACTION("EXCEPTION COMMITTING TRANSACTION");
    private final String value;

    TrjTextTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TrjTextTypes fromValue(String v) {
        for (TrjTextTypes c: TrjTextTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
