//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}trlFuelSeq"/>
 *         &lt;element ref="{}fuelPosition"/>
 *         &lt;element ref="{}trlFuelDepst" minOccurs="0"/>
 *         &lt;element ref="{}fuelProd"/>
 *         &lt;element ref="{}fuelSvcMode"/>
 *         &lt;element ref="{}fuelMOP"/>
 *         &lt;element ref="{}fuelVolume"/>
 *         &lt;element name="trlFuelTaxExemption" type="{}fuelTaxInfoType" minOccurs="0"/>
 *         &lt;element name="trlFuelTaxAddition" type="{}fuelTaxInfoType" minOccurs="0"/>
 *         &lt;element name="trlFuelTaxAdditionByDept" type="{}fuelTaxInfoType" minOccurs="0"/>
 *         &lt;element name="trlFiscalFlatTax" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="sysid" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="taxRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fuelOverrun" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="status" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="manualAdj"/>
 *                       &lt;enumeration value="autoSettle"/>
 *                       &lt;enumeration value="autoAdj"/>
 *                       &lt;enumeration value="pending"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="basePrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="fuelConvAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="cashAcceptor"/>
 *             &lt;enumeration value="autocollect"/>
 *             &lt;enumeration value="refrDisc"/>
 *             &lt;enumeration value="norm"/>
 *             &lt;enumeration value="manualFuel"/>
 *             &lt;enumeration value="manualFuelWithManualDiscount"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trlFuelSeq",
    "fuelPosition",
    "trlFuelDepst",
    "fuelProd",
    "fuelSvcMode",
    "fuelMOP",
    "fuelVolume",
    "trlFuelTaxExemption",
    "trlFuelTaxAddition",
    "trlFuelTaxAdditionByDept",
    "trlFiscalFlatTax",
    "fuelOverrun",
    "basePrice",
    "fuelConvAmt"
})
@XmlRootElement(name = "trlFuel")
public class TrlFuel {

    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger trlFuelSeq;
    protected int fuelPosition;
    protected BigDecimal trlFuelDepst;
    @XmlElement(required = true)
    protected FuelProd fuelProd;
    @XmlElement(required = true)
    protected FuelSvcMode fuelSvcMode;
    @XmlElement(required = true)
    protected FuelMOP fuelMOP;
    @XmlElement(required = true)
    protected BigDecimal fuelVolume;
    protected FuelTaxInfoType trlFuelTaxExemption;
    protected FuelTaxInfoType trlFuelTaxAddition;
    protected FuelTaxInfoType trlFuelTaxAdditionByDept;
    protected List<TrlFuel.TrlFiscalFlatTax> trlFiscalFlatTax;
    protected TrlFuel.FuelOverrun fuelOverrun;
    protected BigDecimal basePrice;
    protected BigDecimal fuelConvAmt;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the trlFuelSeq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrlFuelSeq() {
        return trlFuelSeq;
    }

    /**
     * Sets the value of the trlFuelSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrlFuelSeq(BigInteger value) {
        this.trlFuelSeq = value;
    }

    /**
     * Gets the value of the fuelPosition property.
     * 
     */
    public int getFuelPosition() {
        return fuelPosition;
    }

    /**
     * Sets the value of the fuelPosition property.
     * 
     */
    public void setFuelPosition(int value) {
        this.fuelPosition = value;
    }

    /**
     * Gets the value of the trlFuelDepst property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrlFuelDepst() {
        return trlFuelDepst;
    }

    /**
     * Sets the value of the trlFuelDepst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrlFuelDepst(BigDecimal value) {
        this.trlFuelDepst = value;
    }

    /**
     * Gets the value of the fuelProd property.
     * 
     * @return
     *     possible object is
     *     {@link FuelProd }
     *     
     */
    public FuelProd getFuelProd() {
        return fuelProd;
    }

    /**
     * Sets the value of the fuelProd property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuelProd }
     *     
     */
    public void setFuelProd(FuelProd value) {
        this.fuelProd = value;
    }

    /**
     * Gets the value of the fuelSvcMode property.
     * 
     * @return
     *     possible object is
     *     {@link FuelSvcMode }
     *     
     */
    public FuelSvcMode getFuelSvcMode() {
        return fuelSvcMode;
    }

    /**
     * Sets the value of the fuelSvcMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuelSvcMode }
     *     
     */
    public void setFuelSvcMode(FuelSvcMode value) {
        this.fuelSvcMode = value;
    }

    /**
     * Gets the value of the fuelMOP property.
     * 
     * @return
     *     possible object is
     *     {@link FuelMOP }
     *     
     */
    public FuelMOP getFuelMOP() {
        return fuelMOP;
    }

    /**
     * Sets the value of the fuelMOP property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuelMOP }
     *     
     */
    public void setFuelMOP(FuelMOP value) {
        this.fuelMOP = value;
    }

    /**
     * Gets the value of the fuelVolume property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFuelVolume() {
        return fuelVolume;
    }

    /**
     * Sets the value of the fuelVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFuelVolume(BigDecimal value) {
        this.fuelVolume = value;
    }

    /**
     * Gets the value of the trlFuelTaxExemption property.
     * 
     * @return
     *     possible object is
     *     {@link FuelTaxInfoType }
     *     
     */
    public FuelTaxInfoType getTrlFuelTaxExemption() {
        return trlFuelTaxExemption;
    }

    /**
     * Sets the value of the trlFuelTaxExemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuelTaxInfoType }
     *     
     */
    public void setTrlFuelTaxExemption(FuelTaxInfoType value) {
        this.trlFuelTaxExemption = value;
    }

    /**
     * Gets the value of the trlFuelTaxAddition property.
     * 
     * @return
     *     possible object is
     *     {@link FuelTaxInfoType }
     *     
     */
    public FuelTaxInfoType getTrlFuelTaxAddition() {
        return trlFuelTaxAddition;
    }

    /**
     * Sets the value of the trlFuelTaxAddition property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuelTaxInfoType }
     *     
     */
    public void setTrlFuelTaxAddition(FuelTaxInfoType value) {
        this.trlFuelTaxAddition = value;
    }

    /**
     * Gets the value of the trlFuelTaxAdditionByDept property.
     * 
     * @return
     *     possible object is
     *     {@link FuelTaxInfoType }
     *     
     */
    public FuelTaxInfoType getTrlFuelTaxAdditionByDept() {
        return trlFuelTaxAdditionByDept;
    }

    /**
     * Sets the value of the trlFuelTaxAdditionByDept property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuelTaxInfoType }
     *     
     */
    public void setTrlFuelTaxAdditionByDept(FuelTaxInfoType value) {
        this.trlFuelTaxAdditionByDept = value;
    }

    /**
     * Gets the value of the trlFiscalFlatTax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trlFiscalFlatTax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrlFiscalFlatTax().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrlFuel.TrlFiscalFlatTax }
     * 
     * 
     */
    public List<TrlFuel.TrlFiscalFlatTax> getTrlFiscalFlatTax() {
        if (trlFiscalFlatTax == null) {
            trlFiscalFlatTax = new ArrayList<TrlFuel.TrlFiscalFlatTax>();
        }
        return this.trlFiscalFlatTax;
    }

    /**
     * Gets the value of the fuelOverrun property.
     * 
     * @return
     *     possible object is
     *     {@link TrlFuel.FuelOverrun }
     *     
     */
    public TrlFuel.FuelOverrun getFuelOverrun() {
        return fuelOverrun;
    }

    /**
     * Sets the value of the fuelOverrun property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrlFuel.FuelOverrun }
     *     
     */
    public void setFuelOverrun(TrlFuel.FuelOverrun value) {
        this.fuelOverrun = value;
    }

    /**
     * Gets the value of the basePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBasePrice() {
        return basePrice;
    }

    /**
     * Sets the value of the basePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBasePrice(BigDecimal value) {
        this.basePrice = value;
    }

    /**
     * Gets the value of the fuelConvAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFuelConvAmt() {
        return fuelConvAmt;
    }

    /**
     * Sets the value of the fuelConvAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFuelConvAmt(BigDecimal value) {
        this.fuelConvAmt = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *       &lt;attribute name="status" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="manualAdj"/>
     *             &lt;enumeration value="autoSettle"/>
     *             &lt;enumeration value="autoAdj"/>
     *             &lt;enumeration value="pending"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "amount",
        "volume"
    })
    public static class FuelOverrun {

        @XmlElement(required = true)
        protected BigDecimal amount;
        @XmlElement(required = true)
        protected BigDecimal volume;
        @XmlAttribute(name = "status", required = true)
        protected String status;

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAmount(BigDecimal value) {
            this.amount = value;
        }

        /**
         * Gets the value of the volume property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getVolume() {
            return volume;
        }

        /**
         * Sets the value of the volume property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setVolume(BigDecimal value) {
            this.volume = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="sysid" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="taxRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sysid",
        "name",
        "taxRate",
        "amount"
    })
    public static class TrlFiscalFlatTax {

        @XmlElement(required = true)
        protected BigDecimal sysid;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected BigDecimal taxRate;
        @XmlElement(required = true)
        protected BigDecimal amount;

        /**
         * Gets the value of the sysid property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSysid() {
            return sysid;
        }

        /**
         * Sets the value of the sysid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSysid(BigDecimal value) {
            this.sysid = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the taxRate property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTaxRate() {
            return taxRate;
        }

        /**
         * Sets the value of the taxRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTaxRate(BigDecimal value) {
            this.taxRate = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAmount(BigDecimal value) {
            this.amount = value;
        }

    }

}
