//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}trlTaxes"/>
 *         &lt;element ref="{}trlFee" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}trlFlags"/>
 *         &lt;element ref="{}trlDept" minOccurs="0"/>
 *         &lt;element ref="{}trlCat" minOccurs="0"/>
 *         &lt;element ref="{}trlNetwCode"/>
 *         &lt;element ref="{}trlQty"/>
 *         &lt;element ref="{}trlSign"/>
 *         &lt;element ref="{}trlXQty" minOccurs="0"/>
 *         &lt;element ref="{}trlYQty" minOccurs="0"/>
 *         &lt;element ref="{}trlSellUnit" minOccurs="0"/>
 *         &lt;element ref="{}trlSerialNum" minOccurs="0"/>
 *         &lt;element ref="{}trlVoidLineIx" minOccurs="0"/>
 *         &lt;element ref="{}trlDisc" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}trlPromo" minOccurs="0"/>
 *         &lt;element ref="{}trlUnitPrice"/>
 *         &lt;element ref="{}trlLineTot"/>
 *         &lt;element name="trlPrcOvrd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="trlOvrdCshr" type="{}ovrdCshrType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}trlFuel" minOccurs="0"/>
 *         &lt;element ref="{}trlDesc" minOccurs="0"/>
 *         &lt;element ref="{}trlUPC" minOccurs="0"/>
 *         &lt;element ref="{}trlModifier" minOccurs="0"/>
 *         &lt;element ref="{}trlUPCEntry" minOccurs="0"/>
 *         &lt;element name="trlMO" type="{}trlMO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}trlCw" minOccurs="0"/>
 *         &lt;element ref="{}trlCombo" minOccurs="0"/>
 *         &lt;element ref="{}trlMatch" minOccurs="0"/>
 *         &lt;element name="trlMixMatches" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="trlMatchLine" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="trlMatchNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *                             &lt;element name="trlMatchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="trlMatchQuantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="trlMatchPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="trlMatchPkgAdjAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="trlMatchMixes" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                             &lt;element name="trlPromoAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="trlPromotionID" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="promotype" use="required" type="{}NAXMLPromoType" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="trlPromotionItemListID" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="itemlisttype" use="required" type="{}ItemListType" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}trlPopDisc" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="trlAppSpcfcData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="trlShellLoyalty" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="discType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="discGrade" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="discVolume" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="totDiscAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="trlOrigTickNum" type="{}trTickNum" minOccurs="0"/>
 *         &lt;element name="trlCouponDisc" type="{}couponDiscountType" minOccurs="0"/>
 *         &lt;element ref="{}trlInvItemId" minOccurs="0"/>
 *         &lt;element name="trloLnItemDisc" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="discAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="taxCred" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="programID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="trloPPGDisc" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PPGVol" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="PPGTotDisc" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="PPGOrgPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="PPGGalDisc" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="programID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="plu"/>
 *             &lt;enumeration value="void plu"/>
 *             &lt;enumeration value="postFuel"/>
 *             &lt;enumeration value="void postFuel"/>
 *             &lt;enumeration value="preFuel"/>
 *             &lt;enumeration value="void preFuel"/>
 *             &lt;enumeration value="preFuelCompletion"/>
 *             &lt;enumeration value="void preFuelCompletion"/>
 *             &lt;enumeration value="dept"/>
 *             &lt;enumeration value="void dept"/>
 *             &lt;enumeration value="moneyOrder"/>
 *             &lt;enumeration value="void moneyOrder"/>
 *             &lt;enumeration value="autocollect"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="duplicate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="unsettled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trlTaxes",
    "trlFee",
    "trlFlags",
    "trlDept",
    "trlCat",
    "trlNetwCode",
    "trlQty",
    "trlSign",
    "trlXQty",
    "trlYQty",
    "trlSellUnit",
    "trlSerialNum",
    "trlVoidLineIx",
    "trlDisc",
    "trlPromo",
    "trlUnitPrice",
    "trlLineTot",
    "trlPrcOvrd",
    "trlOvrdCshr",
    "trlFuel",
    "trlDesc",
    "trlUPC",
    "trlModifier",
    "trlUPCEntry",
    "trlMO",
    "trlCw",
    "trlCombo",
    "trlMatch",
    "trlMixMatches",
    "trlPopDisc",
    "trlAppSpcfcData",
    "trlOrigTickNum",
    "trlCouponDisc",
    "trlInvItemId",
    "trloLnItemDisc",
    "trloPPGDisc"
})
@XmlRootElement(name = "trLine")
public class TrLine {

    @XmlElement(required = true)
    protected TrlTaxes trlTaxes;
    protected List<TrlFee> trlFee;
    @XmlElement(required = true)
    protected TrlFlags trlFlags;
    protected TrlDept trlDept;
    protected TrlCat trlCat;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger trlNetwCode;
    @XmlElement(required = true)
    protected BigDecimal trlQty;
    @XmlElement(required = true)
    protected BigDecimal trlSign;
    protected BigDecimal trlXQty;
    protected BigDecimal trlYQty;
    protected BigDecimal trlSellUnit;
    protected String trlSerialNum;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger trlVoidLineIx;
    protected List<TrlDisc> trlDisc;
    protected TrlPromo trlPromo;
    @XmlElement(required = true)
    protected BigDecimal trlUnitPrice;
    @XmlElement(required = true)
    protected BigDecimal trlLineTot;
    protected BigDecimal trlPrcOvrd;
    protected List<OvrdCshrType> trlOvrdCshr;
    protected TrlFuel trlFuel;
    protected String trlDesc;
    protected String trlUPC;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger trlModifier;
    protected TrlUPCEntry trlUPCEntry;
    protected List<TrlMO> trlMO;
    protected TrlCw trlCw;
    protected TrlCombo trlCombo;
    protected TrlMatch trlMatch;
    protected TrLine.TrlMixMatches trlMixMatches;
    protected List<TrlPopDisc> trlPopDisc;
    protected TrLine.TrlAppSpcfcData trlAppSpcfcData;
    protected TrTickNum trlOrigTickNum;
    protected CouponDiscountType trlCouponDisc;
    protected String trlInvItemId;
    protected List<TrLine.TrloLnItemDisc> trloLnItemDisc;
    protected List<TrLine.TrloPPGDisc> trloPPGDisc;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "duplicate")
    protected Boolean duplicate;
    @XmlAttribute(name = "unsettled")
    protected Boolean unsettled;

    /**
     * Gets the value of the trlTaxes property.
     * 
     * @return
     *     possible object is
     *     {@link TrlTaxes }
     *     
     */
    public TrlTaxes getTrlTaxes() {
        return trlTaxes;
    }

    /**
     * Sets the value of the trlTaxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrlTaxes }
     *     
     */
    public void setTrlTaxes(TrlTaxes value) {
        this.trlTaxes = value;
    }

    /**
     * Gets the value of the trlFee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trlFee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrlFee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrlFee }
     * 
     * 
     */
    public List<TrlFee> getTrlFee() {
        if (trlFee == null) {
            trlFee = new ArrayList<TrlFee>();
        }
        return this.trlFee;
    }

    /**
     * Gets the value of the trlFlags property.
     * 
     * @return
     *     possible object is
     *     {@link TrlFlags }
     *     
     */
    public TrlFlags getTrlFlags() {
        return trlFlags;
    }

    /**
     * Sets the value of the trlFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrlFlags }
     *     
     */
    public void setTrlFlags(TrlFlags value) {
        this.trlFlags = value;
    }

    /**
     * Gets the value of the trlDept property.
     * 
     * @return
     *     possible object is
     *     {@link TrlDept }
     *     
     */
    public TrlDept getTrlDept() {
        return trlDept;
    }

    /**
     * Sets the value of the trlDept property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrlDept }
     *     
     */
    public void setTrlDept(TrlDept value) {
        this.trlDept = value;
    }

    /**
     * Gets the value of the trlCat property.
     * 
     * @return
     *     possible object is
     *     {@link TrlCat }
     *     
     */
    public TrlCat getTrlCat() {
        return trlCat;
    }

    /**
     * Sets the value of the trlCat property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrlCat }
     *     
     */
    public void setTrlCat(TrlCat value) {
        this.trlCat = value;
    }

    /**
     * Gets the value of the trlNetwCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrlNetwCode() {
        return trlNetwCode;
    }

    /**
     * Sets the value of the trlNetwCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrlNetwCode(BigInteger value) {
        this.trlNetwCode = value;
    }

    /**
     * Gets the value of the trlQty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrlQty() {
        return trlQty;
    }

    /**
     * Sets the value of the trlQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrlQty(BigDecimal value) {
        this.trlQty = value;
    }

    /**
     * Gets the value of the trlSign property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrlSign() {
        return trlSign;
    }

    /**
     * Sets the value of the trlSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrlSign(BigDecimal value) {
        this.trlSign = value;
    }

    /**
     * Gets the value of the trlXQty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrlXQty() {
        return trlXQty;
    }

    /**
     * Sets the value of the trlXQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrlXQty(BigDecimal value) {
        this.trlXQty = value;
    }

    /**
     * Gets the value of the trlYQty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrlYQty() {
        return trlYQty;
    }

    /**
     * Sets the value of the trlYQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrlYQty(BigDecimal value) {
        this.trlYQty = value;
    }

    /**
     * Gets the value of the trlSellUnit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrlSellUnit() {
        return trlSellUnit;
    }

    /**
     * Sets the value of the trlSellUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrlSellUnit(BigDecimal value) {
        this.trlSellUnit = value;
    }

    /**
     * Gets the value of the trlSerialNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrlSerialNum() {
        return trlSerialNum;
    }

    /**
     * Sets the value of the trlSerialNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrlSerialNum(String value) {
        this.trlSerialNum = value;
    }

    /**
     * Gets the value of the trlVoidLineIx property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrlVoidLineIx() {
        return trlVoidLineIx;
    }

    /**
     * Sets the value of the trlVoidLineIx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrlVoidLineIx(BigInteger value) {
        this.trlVoidLineIx = value;
    }

    /**
     * Gets the value of the trlDisc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trlDisc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrlDisc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrlDisc }
     * 
     * 
     */
    public List<TrlDisc> getTrlDisc() {
        if (trlDisc == null) {
            trlDisc = new ArrayList<TrlDisc>();
        }
        return this.trlDisc;
    }

    /**
     * Gets the value of the trlPromo property.
     * 
     * @return
     *     possible object is
     *     {@link TrlPromo }
     *     
     */
    public TrlPromo getTrlPromo() {
        return trlPromo;
    }

    /**
     * Sets the value of the trlPromo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrlPromo }
     *     
     */
    public void setTrlPromo(TrlPromo value) {
        this.trlPromo = value;
    }

    /**
     * Gets the value of the trlUnitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrlUnitPrice() {
        return trlUnitPrice;
    }

    /**
     * Sets the value of the trlUnitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrlUnitPrice(BigDecimal value) {
        this.trlUnitPrice = value;
    }

    /**
     * Gets the value of the trlLineTot property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrlLineTot() {
        return trlLineTot;
    }

    /**
     * Sets the value of the trlLineTot property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrlLineTot(BigDecimal value) {
        this.trlLineTot = value;
    }

    /**
     * Gets the value of the trlPrcOvrd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrlPrcOvrd() {
        return trlPrcOvrd;
    }

    /**
     * Sets the value of the trlPrcOvrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrlPrcOvrd(BigDecimal value) {
        this.trlPrcOvrd = value;
    }

    /**
     * Gets the value of the trlOvrdCshr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trlOvrdCshr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrlOvrdCshr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OvrdCshrType }
     * 
     * 
     */
    public List<OvrdCshrType> getTrlOvrdCshr() {
        if (trlOvrdCshr == null) {
            trlOvrdCshr = new ArrayList<OvrdCshrType>();
        }
        return this.trlOvrdCshr;
    }

    /**
     * Gets the value of the trlFuel property.
     * 
     * @return
     *     possible object is
     *     {@link TrlFuel }
     *     
     */
    public TrlFuel getTrlFuel() {
        return trlFuel;
    }

    /**
     * Sets the value of the trlFuel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrlFuel }
     *     
     */
    public void setTrlFuel(TrlFuel value) {
        this.trlFuel = value;
    }

    /**
     * Gets the value of the trlDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrlDesc() {
        return trlDesc;
    }

    /**
     * Sets the value of the trlDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrlDesc(String value) {
        this.trlDesc = value;
    }

    /**
     * Gets the value of the trlUPC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrlUPC() {
        return trlUPC;
    }

    /**
     * Sets the value of the trlUPC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrlUPC(String value) {
        this.trlUPC = value;
    }

    /**
     * Gets the value of the trlModifier property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrlModifier() {
        return trlModifier;
    }

    /**
     * Sets the value of the trlModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrlModifier(BigInteger value) {
        this.trlModifier = value;
    }

    /**
     * Gets the value of the trlUPCEntry property.
     * 
     * @return
     *     possible object is
     *     {@link TrlUPCEntry }
     *     
     */
    public TrlUPCEntry getTrlUPCEntry() {
        return trlUPCEntry;
    }

    /**
     * Sets the value of the trlUPCEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrlUPCEntry }
     *     
     */
    public void setTrlUPCEntry(TrlUPCEntry value) {
        this.trlUPCEntry = value;
    }

    /**
     * Gets the value of the trlMO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trlMO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrlMO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrlMO }
     * 
     * 
     */
    public List<TrlMO> getTrlMO() {
        if (trlMO == null) {
            trlMO = new ArrayList<TrlMO>();
        }
        return this.trlMO;
    }

    /**
     * Gets the value of the trlCw property.
     * 
     * @return
     *     possible object is
     *     {@link TrlCw }
     *     
     */
    public TrlCw getTrlCw() {
        return trlCw;
    }

    /**
     * Sets the value of the trlCw property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrlCw }
     *     
     */
    public void setTrlCw(TrlCw value) {
        this.trlCw = value;
    }

    /**
     * Gets the value of the trlCombo property.
     * 
     * @return
     *     possible object is
     *     {@link TrlCombo }
     *     
     */
    public TrlCombo getTrlCombo() {
        return trlCombo;
    }

    /**
     * Sets the value of the trlCombo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrlCombo }
     *     
     */
    public void setTrlCombo(TrlCombo value) {
        this.trlCombo = value;
    }

    /**
     * Gets the value of the trlMatch property.
     * 
     * @return
     *     possible object is
     *     {@link TrlMatch }
     *     
     */
    public TrlMatch getTrlMatch() {
        return trlMatch;
    }

    /**
     * Sets the value of the trlMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrlMatch }
     *     
     */
    public void setTrlMatch(TrlMatch value) {
        this.trlMatch = value;
    }

    /**
     * Gets the value of the trlMixMatches property.
     * 
     * @return
     *     possible object is
     *     {@link TrLine.TrlMixMatches }
     *     
     */
    public TrLine.TrlMixMatches getTrlMixMatches() {
        return trlMixMatches;
    }

    /**
     * Sets the value of the trlMixMatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrLine.TrlMixMatches }
     *     
     */
    public void setTrlMixMatches(TrLine.TrlMixMatches value) {
        this.trlMixMatches = value;
    }

    /**
     * Gets the value of the trlPopDisc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trlPopDisc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrlPopDisc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrlPopDisc }
     * 
     * 
     */
    public List<TrlPopDisc> getTrlPopDisc() {
        if (trlPopDisc == null) {
            trlPopDisc = new ArrayList<TrlPopDisc>();
        }
        return this.trlPopDisc;
    }

    /**
     * Gets the value of the trlAppSpcfcData property.
     * 
     * @return
     *     possible object is
     *     {@link TrLine.TrlAppSpcfcData }
     *     
     */
    public TrLine.TrlAppSpcfcData getTrlAppSpcfcData() {
        return trlAppSpcfcData;
    }

    /**
     * Sets the value of the trlAppSpcfcData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrLine.TrlAppSpcfcData }
     *     
     */
    public void setTrlAppSpcfcData(TrLine.TrlAppSpcfcData value) {
        this.trlAppSpcfcData = value;
    }

    /**
     * Gets the value of the trlOrigTickNum property.
     * 
     * @return
     *     possible object is
     *     {@link TrTickNum }
     *     
     */
    public TrTickNum getTrlOrigTickNum() {
        return trlOrigTickNum;
    }

    /**
     * Sets the value of the trlOrigTickNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrTickNum }
     *     
     */
    public void setTrlOrigTickNum(TrTickNum value) {
        this.trlOrigTickNum = value;
    }

    /**
     * Gets the value of the trlCouponDisc property.
     * 
     * @return
     *     possible object is
     *     {@link CouponDiscountType }
     *     
     */
    public CouponDiscountType getTrlCouponDisc() {
        return trlCouponDisc;
    }

    /**
     * Sets the value of the trlCouponDisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link CouponDiscountType }
     *     
     */
    public void setTrlCouponDisc(CouponDiscountType value) {
        this.trlCouponDisc = value;
    }

    /**
     * Gets the value of the trlInvItemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrlInvItemId() {
        return trlInvItemId;
    }

    /**
     * Sets the value of the trlInvItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrlInvItemId(String value) {
        this.trlInvItemId = value;
    }

    /**
     * Gets the value of the trloLnItemDisc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trloLnItemDisc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrloLnItemDisc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrLine.TrloLnItemDisc }
     * 
     * 
     */
    public List<TrLine.TrloLnItemDisc> getTrloLnItemDisc() {
        if (trloLnItemDisc == null) {
            trloLnItemDisc = new ArrayList<TrLine.TrloLnItemDisc>();
        }
        return this.trloLnItemDisc;
    }

    /**
     * Gets the value of the trloPPGDisc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trloPPGDisc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrloPPGDisc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrLine.TrloPPGDisc }
     * 
     * 
     */
    public List<TrLine.TrloPPGDisc> getTrloPPGDisc() {
        if (trloPPGDisc == null) {
            trloPPGDisc = new ArrayList<TrLine.TrloPPGDisc>();
        }
        return this.trloPPGDisc;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the duplicate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDuplicate() {
        return duplicate;
    }

    /**
     * Sets the value of the duplicate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDuplicate(Boolean value) {
        this.duplicate = value;
    }

    /**
     * Gets the value of the unsettled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUnsettled() {
        return unsettled;
    }

    /**
     * Sets the value of the unsettled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnsettled(Boolean value) {
        this.unsettled = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="trlShellLoyalty" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="discType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="discGrade" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="discVolume" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="totDiscAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trlShellLoyalty"
    })
    public static class TrlAppSpcfcData {

        protected TrLine.TrlAppSpcfcData.TrlShellLoyalty trlShellLoyalty;

        /**
         * Gets the value of the trlShellLoyalty property.
         * 
         * @return
         *     possible object is
         *     {@link TrLine.TrlAppSpcfcData.TrlShellLoyalty }
         *     
         */
        public TrLine.TrlAppSpcfcData.TrlShellLoyalty getTrlShellLoyalty() {
            return trlShellLoyalty;
        }

        /**
         * Sets the value of the trlShellLoyalty property.
         * 
         * @param value
         *     allowed object is
         *     {@link TrLine.TrlAppSpcfcData.TrlShellLoyalty }
         *     
         */
        public void setTrlShellLoyalty(TrLine.TrlAppSpcfcData.TrlShellLoyalty value) {
            this.trlShellLoyalty = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="discType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="discGrade" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="discVolume" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="totDiscAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "discType",
            "discGrade",
            "discVolume",
            "totDiscAmount"
        })
        public static class TrlShellLoyalty {

            @XmlElement(required = true)
            protected BigInteger discType;
            @XmlElement(required = true)
            protected BigInteger discGrade;
            @XmlElement(required = true)
            protected BigDecimal discVolume;
            @XmlElement(required = true)
            protected BigDecimal totDiscAmount;

            /**
             * Gets the value of the discType property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDiscType() {
                return discType;
            }

            /**
             * Sets the value of the discType property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDiscType(BigInteger value) {
                this.discType = value;
            }

            /**
             * Gets the value of the discGrade property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDiscGrade() {
                return discGrade;
            }

            /**
             * Sets the value of the discGrade property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDiscGrade(BigInteger value) {
                this.discGrade = value;
            }

            /**
             * Gets the value of the discVolume property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDiscVolume() {
                return discVolume;
            }

            /**
             * Sets the value of the discVolume property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDiscVolume(BigDecimal value) {
                this.discVolume = value;
            }

            /**
             * Gets the value of the totDiscAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTotDiscAmount() {
                return totDiscAmount;
            }

            /**
             * Sets the value of the totDiscAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTotDiscAmount(BigDecimal value) {
                this.totDiscAmount = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="trlMatchLine" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="trlMatchNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
     *                   &lt;element name="trlMatchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="trlMatchQuantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="trlMatchPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="trlMatchPkgAdjAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="trlMatchMixes" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *                   &lt;element name="trlPromoAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="trlPromotionID" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="promotype" use="required" type="{}NAXMLPromoType" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="trlPromotionItemListID" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="itemlisttype" use="required" type="{}ItemListType" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trlMatchLine"
    })
    public static class TrlMixMatches {

        @XmlElement(required = true)
        protected List<TrLine.TrlMixMatches.TrlMatchLine> trlMatchLine;

        /**
         * Gets the value of the trlMatchLine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the trlMatchLine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTrlMatchLine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TrLine.TrlMixMatches.TrlMatchLine }
         * 
         * 
         */
        public List<TrLine.TrlMixMatches.TrlMatchLine> getTrlMatchLine() {
            if (trlMatchLine == null) {
                trlMatchLine = new ArrayList<TrLine.TrlMixMatches.TrlMatchLine>();
            }
            return this.trlMatchLine;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="trlMatchNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
         *         &lt;element name="trlMatchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="trlMatchQuantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="trlMatchPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="trlMatchPkgAdjAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="trlMatchMixes" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
         *         &lt;element name="trlPromoAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="trlPromotionID" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="promotype" use="required" type="{}NAXMLPromoType" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="trlPromotionItemListID" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="itemlisttype" use="required" type="{}ItemListType" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "trlMatchNumber",
            "trlMatchName",
            "trlMatchQuantity",
            "trlMatchPrice",
            "trlMatchPkgAdjAmt",
            "trlMatchMixes",
            "trlPromoAmount",
            "trlPromotionID",
            "trlPromotionItemListID"
        })
        public static class TrlMatchLine {

            @XmlSchemaType(name = "unsignedInt")
            protected Long trlMatchNumber;
            @XmlElement(required = true)
            protected String trlMatchName;
            @XmlElement(required = true)
            protected BigInteger trlMatchQuantity;
            @XmlElement(required = true)
            protected BigDecimal trlMatchPrice;
            protected BigDecimal trlMatchPkgAdjAmt;
            @XmlSchemaType(name = "unsignedInt")
            protected long trlMatchMixes;
            protected BigDecimal trlPromoAmount;
            protected TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionID trlPromotionID;
            protected TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionItemListID trlPromotionItemListID;

            /**
             * Gets the value of the trlMatchNumber property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getTrlMatchNumber() {
                return trlMatchNumber;
            }

            /**
             * Sets the value of the trlMatchNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setTrlMatchNumber(Long value) {
                this.trlMatchNumber = value;
            }

            /**
             * Gets the value of the trlMatchName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTrlMatchName() {
                return trlMatchName;
            }

            /**
             * Sets the value of the trlMatchName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTrlMatchName(String value) {
                this.trlMatchName = value;
            }

            /**
             * Gets the value of the trlMatchQuantity property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTrlMatchQuantity() {
                return trlMatchQuantity;
            }

            /**
             * Sets the value of the trlMatchQuantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTrlMatchQuantity(BigInteger value) {
                this.trlMatchQuantity = value;
            }

            /**
             * Gets the value of the trlMatchPrice property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTrlMatchPrice() {
                return trlMatchPrice;
            }

            /**
             * Sets the value of the trlMatchPrice property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTrlMatchPrice(BigDecimal value) {
                this.trlMatchPrice = value;
            }

            /**
             * Gets the value of the trlMatchPkgAdjAmt property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTrlMatchPkgAdjAmt() {
                return trlMatchPkgAdjAmt;
            }

            /**
             * Sets the value of the trlMatchPkgAdjAmt property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTrlMatchPkgAdjAmt(BigDecimal value) {
                this.trlMatchPkgAdjAmt = value;
            }

            /**
             * Gets the value of the trlMatchMixes property.
             * 
             */
            public long getTrlMatchMixes() {
                return trlMatchMixes;
            }

            /**
             * Sets the value of the trlMatchMixes property.
             * 
             */
            public void setTrlMatchMixes(long value) {
                this.trlMatchMixes = value;
            }

            /**
             * Gets the value of the trlPromoAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTrlPromoAmount() {
                return trlPromoAmount;
            }

            /**
             * Sets the value of the trlPromoAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTrlPromoAmount(BigDecimal value) {
                this.trlPromoAmount = value;
            }

            /**
             * Gets the value of the trlPromotionID property.
             * 
             * @return
             *     possible object is
             *     {@link TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionID }
             *     
             */
            public TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionID getTrlPromotionID() {
                return trlPromotionID;
            }

            /**
             * Sets the value of the trlPromotionID property.
             * 
             * @param value
             *     allowed object is
             *     {@link TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionID }
             *     
             */
            public void setTrlPromotionID(TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionID value) {
                this.trlPromotionID = value;
            }

            /**
             * Gets the value of the trlPromotionItemListID property.
             * 
             * @return
             *     possible object is
             *     {@link TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionItemListID }
             *     
             */
            public TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionItemListID getTrlPromotionItemListID() {
                return trlPromotionItemListID;
            }

            /**
             * Sets the value of the trlPromotionItemListID property.
             * 
             * @param value
             *     allowed object is
             *     {@link TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionItemListID }
             *     
             */
            public void setTrlPromotionItemListID(TrLine.TrlMixMatches.TrlMatchLine.TrlPromotionItemListID value) {
                this.trlPromotionItemListID = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="promotype" use="required" type="{}NAXMLPromoType" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class TrlPromotionID {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "promotype", required = true)
                protected NAXMLPromoType promotype;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the promotype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link NAXMLPromoType }
                 *     
                 */
                public NAXMLPromoType getPromotype() {
                    return promotype;
                }

                /**
                 * Sets the value of the promotype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link NAXMLPromoType }
                 *     
                 */
                public void setPromotype(NAXMLPromoType value) {
                    this.promotype = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="itemlisttype" use="required" type="{}ItemListType" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class TrlPromotionItemListID {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "itemlisttype", required = true)
                protected ItemListType itemlisttype;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the itemlisttype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ItemListType }
                 *     
                 */
                public ItemListType getItemlisttype() {
                    return itemlisttype;
                }

                /**
                 * Sets the value of the itemlisttype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ItemListType }
                 *     
                 */
                public void setItemlisttype(ItemListType value) {
                    this.itemlisttype = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="discAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="taxCred" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *       &lt;attribute name="programID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "discAmt",
        "qty",
        "taxCred"
    })
    public static class TrloLnItemDisc {

        @XmlElement(required = true)
        protected BigDecimal discAmt;
        @XmlElement(required = true)
        protected BigDecimal qty;
        @XmlElement(required = true)
        protected BigDecimal taxCred;
        @XmlAttribute(name = "programID", required = true)
        protected String programID;

        /**
         * Gets the value of the discAmt property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDiscAmt() {
            return discAmt;
        }

        /**
         * Sets the value of the discAmt property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDiscAmt(BigDecimal value) {
            this.discAmt = value;
        }

        /**
         * Gets the value of the qty property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getQty() {
            return qty;
        }

        /**
         * Sets the value of the qty property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setQty(BigDecimal value) {
            this.qty = value;
        }

        /**
         * Gets the value of the taxCred property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTaxCred() {
            return taxCred;
        }

        /**
         * Sets the value of the taxCred property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTaxCred(BigDecimal value) {
            this.taxCred = value;
        }

        /**
         * Gets the value of the programID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProgramID() {
            return programID;
        }

        /**
         * Sets the value of the programID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProgramID(String value) {
            this.programID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PPGVol" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="PPGTotDisc" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="PPGOrgPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="PPGGalDisc" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *       &lt;attribute name="programID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ppgVol",
        "ppgTotDisc",
        "ppgOrgPrice",
        "ppgGalDisc"
    })
    public static class TrloPPGDisc {

        @XmlElement(name = "PPGVol", required = true)
        protected BigDecimal ppgVol;
        @XmlElement(name = "PPGTotDisc", required = true)
        protected BigDecimal ppgTotDisc;
        @XmlElement(name = "PPGOrgPrice")
        protected BigDecimal ppgOrgPrice;
        @XmlElement(name = "PPGGalDisc", required = true)
        protected BigDecimal ppgGalDisc;
        @XmlAttribute(name = "programID", required = true)
        protected String programID;

        /**
         * Gets the value of the ppgVol property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPPGVol() {
            return ppgVol;
        }

        /**
         * Sets the value of the ppgVol property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPPGVol(BigDecimal value) {
            this.ppgVol = value;
        }

        /**
         * Gets the value of the ppgTotDisc property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPPGTotDisc() {
            return ppgTotDisc;
        }

        /**
         * Sets the value of the ppgTotDisc property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPPGTotDisc(BigDecimal value) {
            this.ppgTotDisc = value;
        }

        /**
         * Gets the value of the ppgOrgPrice property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPPGOrgPrice() {
            return ppgOrgPrice;
        }

        /**
         * Sets the value of the ppgOrgPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPPGOrgPrice(BigDecimal value) {
            this.ppgOrgPrice = value;
        }

        /**
         * Gets the value of the ppgGalDisc property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPPGGalDisc() {
            return ppgGalDisc;
        }

        /**
         * Sets the value of the ppgGalDisc property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPPGGalDisc(BigDecimal value) {
            this.ppgGalDisc = value;
        }

        /**
         * Gets the value of the programID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProgramID() {
            return programID;
        }

        /**
         * Sets the value of the programID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProgramID(String value) {
            this.programID = value;
        }

    }

}
