//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trMixMatch" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="trMMNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="trMMName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trMMPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="trMMDiscount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="trMMSalesLines">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="trMMSalesLine" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="trMMSLNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                                       &lt;element name="trMMSLQuantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="trMMSLPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trMixMatch"
})
@XmlRootElement(name = "trMixMatches")
public class TrMixMatches {

    @XmlElement(required = true)
    protected List<TrMixMatches.TrMixMatch> trMixMatch;

    /**
     * Gets the value of the trMixMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trMixMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrMixMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrMixMatches.TrMixMatch }
     * 
     * 
     */
    public List<TrMixMatches.TrMixMatch> getTrMixMatch() {
        if (trMixMatch == null) {
            trMixMatch = new ArrayList<TrMixMatches.TrMixMatch>();
        }
        return this.trMixMatch;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="trMMNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="trMMName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="trMMPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="trMMDiscount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="trMMSalesLines">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="trMMSalesLine" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="trMMSLNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *                             &lt;element name="trMMSLQuantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="trMMSLPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trMMNumber",
        "trMMName",
        "trMMPrice",
        "trMMDiscount",
        "trMMSalesLines"
    })
    public static class TrMixMatch {

        @XmlElement(required = true)
        protected BigInteger trMMNumber;
        @XmlElement(required = true)
        protected String trMMName;
        @XmlElement(required = true)
        protected BigDecimal trMMPrice;
        @XmlElement(required = true)
        protected BigDecimal trMMDiscount;
        @XmlElement(required = true)
        protected TrMixMatches.TrMixMatch.TrMMSalesLines trMMSalesLines;

        /**
         * Gets the value of the trMMNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTrMMNumber() {
            return trMMNumber;
        }

        /**
         * Sets the value of the trMMNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTrMMNumber(BigInteger value) {
            this.trMMNumber = value;
        }

        /**
         * Gets the value of the trMMName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrMMName() {
            return trMMName;
        }

        /**
         * Sets the value of the trMMName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrMMName(String value) {
            this.trMMName = value;
        }

        /**
         * Gets the value of the trMMPrice property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTrMMPrice() {
            return trMMPrice;
        }

        /**
         * Sets the value of the trMMPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTrMMPrice(BigDecimal value) {
            this.trMMPrice = value;
        }

        /**
         * Gets the value of the trMMDiscount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTrMMDiscount() {
            return trMMDiscount;
        }

        /**
         * Sets the value of the trMMDiscount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTrMMDiscount(BigDecimal value) {
            this.trMMDiscount = value;
        }

        /**
         * Gets the value of the trMMSalesLines property.
         * 
         * @return
         *     possible object is
         *     {@link TrMixMatches.TrMixMatch.TrMMSalesLines }
         *     
         */
        public TrMixMatches.TrMixMatch.TrMMSalesLines getTrMMSalesLines() {
            return trMMSalesLines;
        }

        /**
         * Sets the value of the trMMSalesLines property.
         * 
         * @param value
         *     allowed object is
         *     {@link TrMixMatches.TrMixMatch.TrMMSalesLines }
         *     
         */
        public void setTrMMSalesLines(TrMixMatches.TrMixMatch.TrMMSalesLines value) {
            this.trMMSalesLines = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="trMMSalesLine" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="trMMSLNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
         *                   &lt;element name="trMMSLQuantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="trMMSLPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "trMMSalesLine"
        })
        public static class TrMMSalesLines {

            @XmlElement(required = true)
            protected List<TrMixMatches.TrMixMatch.TrMMSalesLines.TrMMSalesLine> trMMSalesLine;

            /**
             * Gets the value of the trMMSalesLine property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the trMMSalesLine property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTrMMSalesLine().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TrMixMatches.TrMixMatch.TrMMSalesLines.TrMMSalesLine }
             * 
             * 
             */
            public List<TrMixMatches.TrMixMatch.TrMMSalesLines.TrMMSalesLine> getTrMMSalesLine() {
                if (trMMSalesLine == null) {
                    trMMSalesLine = new ArrayList<TrMixMatches.TrMixMatch.TrMMSalesLines.TrMMSalesLine>();
                }
                return this.trMMSalesLine;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="trMMSLNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
             *         &lt;element name="trMMSLQuantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="trMMSLPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "trMMSLNumber",
                "trMMSLQuantity",
                "trMMSLPrice"
            })
            public static class TrMMSalesLine {

                @XmlSchemaType(name = "unsignedInt")
                protected long trMMSLNumber;
                @XmlElement(required = true)
                protected BigInteger trMMSLQuantity;
                @XmlElement(required = true)
                protected BigDecimal trMMSLPrice;

                /**
                 * Gets the value of the trMMSLNumber property.
                 * 
                 */
                public long getTrMMSLNumber() {
                    return trMMSLNumber;
                }

                /**
                 * Sets the value of the trMMSLNumber property.
                 * 
                 */
                public void setTrMMSLNumber(long value) {
                    this.trMMSLNumber = value;
                }

                /**
                 * Gets the value of the trMMSLQuantity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getTrMMSLQuantity() {
                    return trMMSLQuantity;
                }

                /**
                 * Sets the value of the trMMSLQuantity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setTrMMSLQuantity(BigInteger value) {
                    this.trMMSLQuantity = value;
                }

                /**
                 * Gets the value of the trMMSLPrice property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getTrMMSLPrice() {
                    return trMMSLPrice;
                }

                /**
                 * Sets the value of the trMMSLPrice property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setTrMMSLPrice(BigDecimal value) {
                    this.trMMSLPrice = value;
                }

            }

        }

    }

}
