//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}trTotNoTax" minOccurs="0"/>
 *         &lt;element ref="{}trTotWTax" minOccurs="0"/>
 *         &lt;element ref="{}trTotTax" minOccurs="0"/>
 *         &lt;element ref="{}trTax" minOccurs="0"/>
 *         &lt;element ref="{}trCurrTot" minOccurs="0"/>
 *         &lt;element ref="{}trSTotalizer" minOccurs="0"/>
 *         &lt;element ref="{}trGTotalizer" minOccurs="0"/>
 *         &lt;element ref="{}trFstmp" minOccurs="0"/>
 *         &lt;element ref="{}trSpDisc" minOccurs="0"/>
 *         &lt;element ref="{}trCshBk" minOccurs="0"/>
 *         &lt;element ref="{}custDOB" minOccurs="0"/>
 *         &lt;element ref="{}recallAmt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trTotNoTax",
    "trTotWTax",
    "trTotTax",
    "trTax",
    "trCurrTot",
    "trSTotalizer",
    "trGTotalizer",
    "trFstmp",
    "trSpDisc",
    "trCshBk",
    "custDOB",
    "recallAmt"
})
@XmlRootElement(name = "trValue")
public class TrValue {

    protected BigDecimal trTotNoTax;
    protected BigDecimal trTotWTax;
    protected BigDecimal trTotTax;
    protected TrTax trTax;
    protected TrCurrTot trCurrTot;
    protected BigDecimal trSTotalizer;
    protected BigDecimal trGTotalizer;
    protected TrFstmp trFstmp;
    protected TrSpDisc trSpDisc;
    protected TrCshBk trCshBk;
    protected CustDOBCType custDOB;
    protected BigDecimal recallAmt;

    /**
     * Gets the value of the trTotNoTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrTotNoTax() {
        return trTotNoTax;
    }

    /**
     * Sets the value of the trTotNoTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrTotNoTax(BigDecimal value) {
        this.trTotNoTax = value;
    }

    /**
     * Gets the value of the trTotWTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrTotWTax() {
        return trTotWTax;
    }

    /**
     * Sets the value of the trTotWTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrTotWTax(BigDecimal value) {
        this.trTotWTax = value;
    }

    /**
     * Gets the value of the trTotTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrTotTax() {
        return trTotTax;
    }

    /**
     * Sets the value of the trTotTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrTotTax(BigDecimal value) {
        this.trTotTax = value;
    }

    /**
     * Gets the value of the trTax property.
     * 
     * @return
     *     possible object is
     *     {@link TrTax }
     *     
     */
    public TrTax getTrTax() {
        return trTax;
    }

    /**
     * Sets the value of the trTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrTax }
     *     
     */
    public void setTrTax(TrTax value) {
        this.trTax = value;
    }

    /**
     * Gets the value of the trCurrTot property.
     * 
     * @return
     *     possible object is
     *     {@link TrCurrTot }
     *     
     */
    public TrCurrTot getTrCurrTot() {
        return trCurrTot;
    }

    /**
     * Sets the value of the trCurrTot property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrCurrTot }
     *     
     */
    public void setTrCurrTot(TrCurrTot value) {
        this.trCurrTot = value;
    }

    /**
     * Gets the value of the trSTotalizer property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrSTotalizer() {
        return trSTotalizer;
    }

    /**
     * Sets the value of the trSTotalizer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrSTotalizer(BigDecimal value) {
        this.trSTotalizer = value;
    }

    /**
     * Gets the value of the trGTotalizer property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrGTotalizer() {
        return trGTotalizer;
    }

    /**
     * Sets the value of the trGTotalizer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrGTotalizer(BigDecimal value) {
        this.trGTotalizer = value;
    }

    /**
     * Gets the value of the trFstmp property.
     * 
     * @return
     *     possible object is
     *     {@link TrFstmp }
     *     
     */
    public TrFstmp getTrFstmp() {
        return trFstmp;
    }

    /**
     * Sets the value of the trFstmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrFstmp }
     *     
     */
    public void setTrFstmp(TrFstmp value) {
        this.trFstmp = value;
    }

    /**
     * Gets the value of the trSpDisc property.
     * 
     * @return
     *     possible object is
     *     {@link TrSpDisc }
     *     
     */
    public TrSpDisc getTrSpDisc() {
        return trSpDisc;
    }

    /**
     * Sets the value of the trSpDisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrSpDisc }
     *     
     */
    public void setTrSpDisc(TrSpDisc value) {
        this.trSpDisc = value;
    }

    /**
     * Gets the value of the trCshBk property.
     * 
     * @return
     *     possible object is
     *     {@link TrCshBk }
     *     
     */
    public TrCshBk getTrCshBk() {
        return trCshBk;
    }

    /**
     * Sets the value of the trCshBk property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrCshBk }
     *     
     */
    public void setTrCshBk(TrCshBk value) {
        this.trCshBk = value;
    }

    /**
     * Gets the value of the custDOB property.
     * 
     * @return
     *     possible object is
     *     {@link CustDOBCType }
     *     
     */
    public CustDOBCType getCustDOB() {
        return custDOB;
    }

    /**
     * Sets the value of the custDOB property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustDOBCType }
     *     
     */
    public void setCustDOB(CustDOBCType value) {
        this.custDOB = value;
    }

    /**
     * Gets the value of the recallAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRecallAmt() {
        return recallAmt;
    }

    /**
     * Sets the value of the recallAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRecallAmt(BigDecimal value) {
        this.recallAmt = value;
    }

}
