//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for baseCashierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="baseCashierType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="sysid" use="required" type="{}sysidType" />
 *       &lt;attribute name="empNum" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="posNum" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="period" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="drawer" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="attendantID" type="{}attendantIDType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "baseCashierType", propOrder = {
    "value"
})
public class BaseCashierType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "sysid", required = true)
    protected BigInteger sysid;
    @XmlAttribute(name = "empNum", required = true)
    protected String empNum;
    @XmlAttribute(name = "posNum", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger posNum;
    @XmlAttribute(name = "period", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger period;
    @XmlAttribute(name = "drawer")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger drawer;
    @XmlAttribute(name = "attendantID")
    protected String attendantID;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the sysid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSysid() {
        return sysid;
    }

    /**
     * Sets the value of the sysid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSysid(BigInteger value) {
        this.sysid = value;
    }

    /**
     * Gets the value of the empNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpNum() {
        return empNum;
    }

    /**
     * Sets the value of the empNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpNum(String value) {
        this.empNum = value;
    }

    /**
     * Gets the value of the posNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPosNum() {
        return posNum;
    }

    /**
     * Sets the value of the posNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPosNum(BigInteger value) {
        this.posNum = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPeriod(BigInteger value) {
        this.period = value;
    }

    /**
     * Gets the value of the drawer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDrawer() {
        return drawer;
    }

    /**
     * Sets the value of the drawer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDrawer(BigInteger value) {
        this.drawer = value;
    }

    /**
     * Gets the value of the attendantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttendantID() {
        return attendantID;
    }

    /**
     * Sets the value of the attendantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttendantID(String value) {
        this.attendantID = value;
    }

}
