//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for couponDiscountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="couponDiscountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="discountAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="affectsTax" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="entryMethod" type="{}couponEntryMethod"/>
 *         &lt;element name="couponData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "couponDiscountType", propOrder = {
    "discountAmt",
    "affectsTax",
    "entryMethod",
    "couponData"
})
public class CouponDiscountType {

    @XmlElement(required = true)
    protected BigDecimal discountAmt;
    protected boolean affectsTax;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CouponEntryMethod entryMethod;
    @XmlElement(required = true)
    protected String couponData;

    /**
     * Gets the value of the discountAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountAmt() {
        return discountAmt;
    }

    /**
     * Sets the value of the discountAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountAmt(BigDecimal value) {
        this.discountAmt = value;
    }

    /**
     * Gets the value of the affectsTax property.
     * 
     */
    public boolean isAffectsTax() {
        return affectsTax;
    }

    /**
     * Sets the value of the affectsTax property.
     * 
     */
    public void setAffectsTax(boolean value) {
        this.affectsTax = value;
    }

    /**
     * Gets the value of the entryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CouponEntryMethod }
     *     
     */
    public CouponEntryMethod getEntryMethod() {
        return entryMethod;
    }

    /**
     * Sets the value of the entryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CouponEntryMethod }
     *     
     */
    public void setEntryMethod(CouponEntryMethod value) {
        this.entryMethod = value;
    }

    /**
     * Gets the value of the couponData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponData() {
        return couponData;
    }

    /**
     * Sets the value of the couponData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponData(String value) {
        this.couponData = value;
    }

}
