//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.07 at 01:19:54 PM IST 
//


package com.transset;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trExNetProd" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="trENPPcode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="trENPAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="trENPItemCnt" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trExNetProd"
})
@XmlRootElement(name = "trExNetProds")
public class TrExNetProds {

    @XmlElement(required = true)
    protected List<TrExNetProds.TrExNetProd> trExNetProd;

    /**
     * Gets the value of the trExNetProd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trExNetProd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrExNetProd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrExNetProds.TrExNetProd }
     * 
     * 
     */
    public List<TrExNetProds.TrExNetProd> getTrExNetProd() {
        if (trExNetProd == null) {
            trExNetProd = new ArrayList<TrExNetProds.TrExNetProd>();
        }
        return this.trExNetProd;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="trENPPcode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="trENPAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="trENPItemCnt" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trENPPcode",
        "trENPAmount",
        "trENPItemCnt"
    })
    public static class TrExNetProd {

        @XmlElement(required = true)
        protected BigInteger trENPPcode;
        @XmlElement(required = true)
        protected BigDecimal trENPAmount;
        @XmlElement(required = true)
        protected BigInteger trENPItemCnt;

        /**
         * Gets the value of the trENPPcode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTrENPPcode() {
            return trENPPcode;
        }

        /**
         * Sets the value of the trENPPcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTrENPPcode(BigInteger value) {
            this.trENPPcode = value;
        }

        /**
         * Gets the value of the trENPAmount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTrENPAmount() {
            return trENPAmount;
        }

        /**
         * Sets the value of the trENPAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTrENPAmount(BigDecimal value) {
            this.trENPAmount = value;
        }

        /**
         * Gets the value of the trENPItemCnt property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTrENPItemCnt() {
            return trENPItemCnt;
        }

        /**
         * Sets the value of the trENPItemCnt property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTrENPItemCnt(BigInteger value) {
            this.trENPItemCnt = value;
        }

    }

}
