package com.verifone.isd.vsms2.sys.ent.managedevices;

/**
 * This Enum holds the different status messages for Device Registration
 * @author T_VaishnaviS1
 *
 */
public enum ManageDeviceStatusEnum {
	
	 NOT_REGISTERED,				
	 REGISTRATION_SUCCESS,	
	 RE_REGISTRATION_SUCCESS,		
	 REGISTRATION_FAILURE,		
	 RE_REGISTRATION_FAILURE,	
	 REGISTRATION_CONNECTION_ERR,		
	 RE_REGISTRATION_CONNECTION_ERR,		
	 REGISTRATION_TIMEOUT,			
	 RE_REGISTRATION_TIMEOUT,		
	 INVALID_TERMINAL_ID,	
	 TERMINAL_DISABLED,
	 REGISTRATION_FAILURE_MISSING_DATA,
	 RE_REGISTRATION_FAILURE_MISSING_DATA,
	 REGISTRATION_FAILURE_INVALID_DATA,
	 RE_REGISTRATION_FAILURE_INVALID_DATA
}
